(()=>{'use strict';const game=document.currentScript?.dataset.game;if(!game)return;const excluded=()=>{try{return localStorage.getItem('yg-usage-excluded')==='1'}catch{return false}};if(excluded())return;const endpoint='https://imori-no-mainichi.vercel.app/api/usage-collector';const uuid=()=>crypto.randomUUID();let visitor;try{visitor=localStorage.getItem('yg-usage-visitor');if(!visitor){visitor=uuid();localStorage.setItem('yg-usage-visitor',visitor)}}catch{visitor=uuid()}let session=uuid(),day=Math.floor((Date.now()+32400000)/86400000),seconds=0,lastTick=performance.now(),lastInput=0,pending=false,account=null,loggedIn=false,displayName=null,identityKnown=false;
const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(game+':'+value)))).map(b=>b.toString(16).padStart(2,'0')).join('');
async function identity(){if(excluded())return;let id=null,name=null,known=true;try{const keys={toilet:'tw.token',haikyo:'h4.token',gaon:'vmon:token',voraz:'bba_token',imori:'imori:token',shikyou:'shikyou:token',haku:'haku:token',koku:'koku:token',haikou:'haikou-obake:token',nora:'michi:token'};if(keys[game]){const token=localStorage.getItem(keys[game]);if(token){const r=await fetch('/api/usage-identity',{headers:{Authorization:'Bearer '+token},cache:'no-store',signal:AbortSignal.timeout(7000)});if(r.ok){const d=await r.json();id=d.id;name=d.displayName;}else if(r.status!==401)known=false;}}
if(game==='punmu'){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('sb-')&&k.endsWith('-auth-token')){const d=JSON.parse(localStorage.getItem(k)||'null');if(d?.user&&d.expires_at*1000>Date.now()){id=d.user.id;const r=await fetch('https://jnrsqoklxcruvbjaohau.supabase.co/rest/v1/profiles?select=display_name&id=eq.'+encodeURIComponent(id),{headers:{apikey:'sb_publishable_ez7aUzUw8QjQdlssdYS4aA_etkePqNE',Authorization:'Bearer '+d.access_token},signal:AbortSignal.timeout(7000)});if(r.ok){const rows=await r.json();name=rows[0]?.display_name;}else known=false;}}}}
if(['vi','obaketto','komorebi'].includes(game)){const r=await fetch(game==='obaketto'?'/api/auth/session':'/api/usage-identity',{cache:'no-store',signal:AbortSignal.timeout(7000)});if(r.ok){const d=await r.json();id=d.id||d.user?.id;name=d.displayName||d.user?.displayName;}else if(r.status!==401)known=false;}
}catch{known=false}const nextAccount=id?await hash(String(id)):null;if(excluded())return;loggedIn=!!id;account=nextAccount;displayName=id&&typeof name==='string'?name.slice(0,40):null;identityKnown=known;}
const input=()=>{lastInput=Date.now()};['pointerdown','pointermove','keydown','touchstart','wheel'].forEach(k=>addEventListener(k,input,{passive:true}));const active=()=>!excluded()&&!document.hidden&&document.hasFocus()&&Date.now()-lastInput<60000;
setInterval(()=>{const now=performance.now();if(active())seconds+=Math.min((now-lastTick)/1000,2);lastTick=now;},1000);
async function send(){if(excluded()||pending)return;const nextDay=Math.floor((Date.now()+32400000)/86400000);if(nextDay!==day){day=nextDay;seconds=0;session=uuid()}pending=true;try{await identity();if(excluded())return;await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game,session,visitor,day,seconds:Math.floor(seconds),active:active(),loggedIn,account,displayName,identityKnown}),keepalive:true,credentials:'omit'});}catch{}finally{pending=false}}
setInterval(send,30000);addEventListener('visibilitychange',send);addEventListener('pagehide',send);setTimeout(send,1000);
})();
