(()=>{'use strict';const game=document.currentScript?.dataset.game;if(!game)return;const excluded=()=>{try{return localStorage.getItem('yg-usage-excluded')==='1'}catch{return false}};if(excluded())return;const endpoint='https://imori-no-mainichi.vercel.app/api/usage-collector';const uuid=()=>crypto.randomUUID();let visitor;try{visitor=localStorage.getItem('yg-usage-visitor');if(!visitor){visitor=uuid();localStorage.setItem('yg-usage-visitor',visitor)}}catch{visitor=uuid()}let session=uuid(),day=Math.floor((Date.now()+32400000)/86400000),seconds=0,lastTick=performance.now(),lastInput=0,pending=false,account=null,loggedIn=false;
const hash=async value=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(game+':'+value)))).map(b=>b.toString(16).padStart(2,'0')).join('');
async function identity(){if(excluded())return;try{let id=null;const keys={imori:'imori:token',shikyou:'shikyou:token',haku:'haku:token',koku:'koku:token',haikou:'haikou-obake:token',nora:'michi:token'};if(keys[game]){const token=localStorage.getItem(keys[game]);if(token){const b=JSON.parse(atob(token.split('.')[0].replace(/-/g,'+').replace(/_/g,'/')));if(b.exp>Date.now())id=b.id;}}
if(game==='punmu'){for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('sb-')&&k.endsWith('-auth-token')){const d=JSON.parse(localStorage.getItem(k)||'null');if(d?.user&&d.expires_at*1000>Date.now())id=d.user.id;}}}
if(game==='vi'||game==='obaketto'){const r=await fetch(game==='vi'?'/api/usage-identity':'/api/auth/session',{cache:'no-store'});if(r.ok){const d=await r.json();id=d.id||d.user?.id;}}
loggedIn=!!id;account=id?await hash(String(id)):null;}catch{loggedIn=false;account=null}}
const input=()=>{lastInput=Date.now()};['pointerdown','pointermove','keydown','touchstart','wheel'].forEach(k=>addEventListener(k,input,{passive:true}));const active=()=>!excluded()&&!document.hidden&&document.hasFocus()&&Date.now()-lastInput<60000;
setInterval(()=>{const now=performance.now();if(active())seconds+=Math.min((now-lastTick)/1000,2);lastTick=now;},1000);
async function send(){if(excluded()||pending)return;const nextDay=Math.floor((Date.now()+32400000)/86400000);if(nextDay!==day){day=nextDay;seconds=0;session=uuid()}pending=true;try{await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({game,session,visitor,day,seconds:Math.floor(seconds),active:active(),loggedIn,account}),keepalive:true,credentials:'omit'});}catch{}finally{pending=false}}
identity();setInterval(identity,60000);setInterval(send,30000);addEventListener('visibilitychange',send);addEventListener('pagehide',send);setTimeout(send,1000);
})();
