import * as THREE from '../lib/three.module.js';
const root=new URL('../assets/cc0/',import.meta.url);
const texLoader=new THREE.TextureLoader();
const texture=(name,color=true)=>{const t=texLoader.load(new URL(name,root).href);t.flipY=false;if(color)t.colorSpace=THREE.SRGBColorSpace;return t;};
const faceMap=texture('face.webp'),faceNormal=texture('face-normal.webp',false),bodyMap=texture('body.webp'),mouthMap=texture('mouth.webp');
let dataPromise;
function data(){return dataPromise ||= Promise.all([fetch(new URL('human.json',root)).then(r=>{if(!r.ok)throw Error('CC0 mesh metadata');return r.json()}),fetch(new URL('human.bin',root)).then(r=>{if(!r.ok)throw Error('CC0 mesh data');return r.arrayBuffer()})]);}
function geometry(d,bin){const array=a=>new ({Float32Array,Uint16Array,Uint32Array,Uint8Array}[a.type])(bin,a.offset,a.length).slice();const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(array(d.position),3));g.setAttribute('uv',new THREE.BufferAttribute(array(d.uv),2));g.setIndex(new THREE.BufferAttribute(array(d.index),1));const names=Object.keys(d.morphs);if(names.length){g.morphAttributes.position=names.map(n=>{const a=new THREE.BufferAttribute(array(d.morphs[n]),3);a.name=n;return a;});g.morphTargetsRelative=true;}g.computeVertexNormals();return g;}
export function cc0Head(haunted=false){const group=new THREE.Group();group.name=haunted?'cc0-ghost-head':'cc0-protagonist-head';group.userData.ready=data().then(([j,bin])=>{
 const faces=[];
 for(const d of j.head){const geo=geometry(d,bin),mouth=d.name==='VitMouth';const mat=new THREE.MeshStandardMaterial({map:mouth?mouthMap:faceMap,normalMap:mouth?null:faceNormal,normalScale:new THREE.Vector2(.4,.4),color:haunted?0xa6aba3:0xffffff,roughness:haunted?.72:.57});
 if(haunted&&!mouth){const p=geo.attributes.position,c=new Float32Array(p.count*3);for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i),z=p.getZ(i),eye=Math.exp(-(((Math.abs(x)-.033)/.029)**2+((y-1.634)/.025)**2))*Math.max(0,Math.min(1,z/.035));const lip=Math.exp(-((x/.035)**2+((y-1.568)/.015)**2))*Math.max(0,Math.min(1,z/.05));c[i*3]=(1-eye*.82)*(1-lip*.65);c[i*3+1]=(1-eye*.9)*(1-lip*.85);c[i*3+2]=(1-eye*.88)*(1-lip*.8);}geo.setAttribute('color',new THREE.BufferAttribute(c,3));mat.vertexColors=true;}
 if(haunted&&!mouth)mat.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace("#include <color_fragment>","#include <color_fragment>\n float pallor=dot(diffuseColor.rgb,vec3(.299,.587,.114)); diffuseColor.rgb=mix(vec3(pallor*1.55,pallor*1.62,pallor*1.57),diffuseColor.rgb,.08);");};
 const mesh=new THREE.Mesh(geo,mat);group.add(mesh);faces.push(mesh);
 if(!mouth){const hairGeo=geo.clone(),p=geo.attributes.position,ids=[];for(let i=0;i<geo.index.count;i+=3){const a=geo.index.getX(i),b=geo.index.getX(i+1),c=geo.index.getX(i+2),y=(p.getY(a)+p.getY(b)+p.getY(c))/3,z=(p.getZ(a)+p.getZ(b)+p.getZ(c))/3;if(y>1.706||(y>1.655&&z<-.028)||(haunted&&y>1.59&&z<-.035))ids.push(a,b,c);}hairGeo.setIndex(ids);const hair=new THREE.Mesh(hairGeo,new THREE.MeshStandardMaterial({color:0x191516,roughness:.85}));hair.scale.set(1.012,1.003,1.012);group.add(hair);}
 }
 for(const x of [-.03347,.03347]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.0145,20,12),new THREE.MeshStandardMaterial({color:haunted?0xcac8ad:0xddd8ce,roughness:.25}));eye.position.set(x,1.6344,.04676);group.add(eye);const iris=new THREE.Mesh(new THREE.CircleGeometry(.0062,20),new THREE.MeshStandardMaterial({color:haunted?0x9daba4:0x4b3828,roughness:.32}));iris.position.set(x,1.6344,.0614);group.add(iris);const pupil=new THREE.Mesh(new THREE.CircleGeometry(haunted?.0018:.0031,16),new THREE.MeshBasicMaterial({color:0x060505}));pupil.position.set(x,1.6344,.0616);group.add(pupil);}
 if(haunted){const hairMat=new THREE.MeshStandardMaterial({color:0x0c0b0c,roughness:.48});for(const side of [-1,1])for(let i=0;i<14;i++){const x=side*(.033+i*.004),z=.026+Math.sin(i*.6)*.014;const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(x*.7,1.722,z),new THREE.Vector3(x,1.663,.066),new THREE.Vector3(side*(.075+i*.002),1.49,.036),new THREE.Vector3(side*(.07+i*.003),1.3+(i%4)*.024,.006)]);group.add(new THREE.Mesh(new THREE.TubeGeometry(curve,15,.0022+(i%3)*.0005,4,false),hairMat));}}
 if(haunted){const mat=new THREE.MeshStandardMaterial({color:0x100d10,roughness:.65});for(let i=0;i<52;i++){const a=Math.PI+i/51*Math.PI,x=Math.cos(a)*.085,z=Math.sin(a)*.09-.025;const curve=new THREE.CatmullRomCurve3([new THREE.Vector3(x,1.697,z),new THREE.Vector3(x*1.13,1.56,z*1.1),new THREE.Vector3(x*1.2,1.35,z*.8-.02),new THREE.Vector3(x*1.15,1.22+(i%5)*.018,z*.7)]);group.add(new THREE.Mesh(new THREE.TubeGeometry(curve,14,.0032,4,false),mat));}}
 group.userData.animate=(time,strength=0)=>{for(const mesh of faces){const d=mesh.morphTargetDictionary,v=mesh.morphTargetInfluences;v[d.Angry]=haunted?.55+strength*.3:0;v[d.Jaw_Lower]=haunted?.22+strength*.55:0;v[d.Mouth_Large_Opened]=haunted?strength*.4:0;v[d.Eyes_Closed_Max]=haunted?0:Math.pow(Math.max(0,Math.sin(time*.85)),40)*.9;}};
 group.userData.animate(0,haunted?.25:0);return group;
 }).catch(e=>{group.userData.error=e.message;console.warn(e);});return group;}
export function cc0Person(){const group=new THREE.Group();group.name='cc0-protagonist';const head=cc0Head();group.add(head);group.userData.head=head;
 group.userData.ready=Promise.all([head.userData.ready,data().then(([j,bin])=>{for(const d of j.body){const skin=d.name==='VitBody',color=skin?0xffffff:d.name==='VitShirt'?0x4b565e:d.name==='VitPants'?0x24272e:0x211d1b;group.add(new THREE.Mesh(geometry(d,bin),new THREE.MeshStandardMaterial({map:skin?bodyMap:null,color,roughness:.85})));}})]);return group;}
