// English display text. Save IDs and gameplay data remain language-independent.
export const EN = {
  "サーバーに接続できませんでした。通信の状態を確かめてください。": "Could not connect to the server. Please check your connection.",
  "サーバー機能が見つかりません。公開URLで開いてください。": "Server features are unavailable here. Please open the published game URL.",
  "うまくいきませんでした（": "Something went wrong (",
  "階": "F",
  "八月": "August",
  "かぞく": "family",
  "ログイン": "Log in",
  "はじめる": "Start",
  "この端末で はじめる": "Play on this device",
  "名前（またはメール）と合言葉を入れてください。": "Enter your name (or email) and passphrase.",
  "確かめています…": "Checking…",
  "名前を入れてください。": "Enter a name.",
  "合言葉は4文字以上にしてください。": "Use a passphrase of at least 4 characters.",
  "登録しています…": "Creating account…",
  "はじめから": "From the beginning",
  "一階": "1F",
  "　／　見つけたもの ": " / Found: ",
  "分": " min",
  "記録を読んでいます…": "Loading your save…",
  "この端末の記録を、クラウドに預けました。": "Your local progress has been saved to the cloud.",
  "この端末では画面を描き始められませんでした。ブラウザを新しくするか、別の端末でお試しください。（": "Unable to start the game display. Please update your browser or try another device. (",
  "原因不明": "Unknown cause",
  "ログインしました。どの端末でも続けられます。": "You are logged in. You can continue on another device.",
  "📱 この端末だけ": "This device only",
  "ログイン中": "Logged in",
  "ログインしていません": "Not logged in",
  "プレイヤー": "Player",
  "部屋の主": "Host",
  "中継でつながった": "Connected via relay",
  "つながった": "Connected",
  "つないでいます…": "Connecting…",
  "友達を待っています…": "Waiting for friends…",
  "はじめる（": "Start (",
  "人）": " players)",
  "部屋の主が始めるのを待っています…": "Waiting for the host to start…",
  "部屋をつくっています…": "Creating room…",
  "で遊びます": " selected",
  "合言葉は4文字です。": "The room code must be 4 characters.",
  "その部屋を探しています…": "Looking for that room…",
  "つながりました。部屋の主が始めるのを待ちましょう。": "Connected. Waiting for the host to start.",
  " さん、おかえりなさい。": ", welcome back.",
  "ホスト": "Host",
  "つながりませんでした。通信の状態を確かめてください。": "Could not connect. Please check your connection.",
  "——台所で、鍋が落ちた。": "—A pot fell in the kitchen.",
  "……さっきまで、こんな靴は無かった。": "…Those shoes weren't here a moment ago.",
  "……壁が、濡れている。": "…The wall is wet.",
  "……どこかの扉が、揺れている。": "…Somewhere, a door is shaking.",
  "閉める": "Close",
  "開ける": "Open",
  "……閉まったままの扉の下から、灯りが漏れている。": "…Light is spilling out from beneath a closed door.",
  "それ": "The Presence",
  "住人": "Resident",
  "住人を全員つかまえろ。音の波紋が見える。": "Catch every resident. You can see ripples made by their sounds.",
  "鍵を三本あつめて、階段室から出る。走れば聞かれる。": "Collect three keys and escape through the stairwell. Running can be heard.",
  "だれか": "Someone",
  "つかまった。仲間が来るまで動けない。": "You were caught. Wait for a teammate to rescue you.",
  " がつかまった。": " was caught.",
  "助けてもらった。": "You were rescued.",
  " が起きあがった。": " got back up.",
  "……連れて行かれた。": "…Taken away.",
  " が連れて行かれた。": " was taken away.",
  "鍵 ": "Keys ",
  "　階段室へ！": " — Get to the stairs!",
  "時間切れ": "Time's up",
  "全員つかまった": "Everyone was caught",
  "逃げきった": "Escaped",
  "夜が明けはじめた。": "Dawn is breaking.",
  "廊下に、誰の姿もない。": "There is no one left in the corridor.",
  "郵便受けの札が、一枚ずつ増えている。": "Nameplates appear on the mailboxes, one by one.",
  "廊下の照明が、一本ずつ点いていく。": "The corridor lights come on, one by one.",
  "郵便受けに、名前の札が増えている。": "Another nameplate appears on a mailbox.",
  "鉄扉を押し開けて、外に出た。": "I pushed open the iron door and stepped outside.",
  "うしろで、扉が閉まる音がした。": "Behind me, I heard the door close.",
  "　——勝ち": " — WIN",
  "　——負け": " — LOSE",
  "　のこり ": " — Remaining: ",
  "人": " players",
  "　鍵 ": " / Keys ",
  "　あと": " / Left: ",
  "回": " times",
  "音声を取得できません: {0}": "Could not load audio: {0}",
  "突然の出現（Sudden Terror）": "Sudden appearance (Sudden Terror)",
  "足音（歩く）": "Footsteps (walking)",
  "足音（走る）": "Footsteps (running)",
  "足音（しゃがむ）": "Footsteps (crouching)",
  "階段": "Stairs",
  "扉を開ける": "Open door",
  "扉を閉める": "Close door",
  "鍵がかかっている": "Locked door",
  "扉が勢いよく閉まる": "Door slamming",
  "紙をめくる": "Turning pages",
  "引き出し・押し入れ": "Drawer / closet",
  "袋がこすれる": "Rustling bag",
  "床がきしむ": "Creaking floor",
  "鍋が落ちる": "Falling pot",
  "拾う": "Pick up",
  "懐中電灯": "Flashlight",
  "分電盤のつまみ": "Circuit breaker switch",
  "水が一滴": "Water drop",
  "蛍光灯が切れる": "Fluorescent tube going out",
  "外廊下の風": "Wind in the corridor",
  "遠くの物音": "Distant noise",
  "戸を叩く音": "Knocking on a door",
  "廊下を通る足音": "Passing footsteps",
  "裸足でついてくる": "Bare feet following you",
  "濡れた服を引きずる": "Dragging wet clothes",
  "冷蔵庫の内側": "Inside the refrigerator",
  "品物": "Item",
  "を取る": " — Take",
  "読む": "Read",
  "手に取る": "Pick up",
  "調べる": "Inspect",
  "を開ける": " — Open",
  "トイレ": "Toilet",
  "風呂": "Bathroom",
  "トイレの鏡を覗く": "Look into the toilet mirror",
  "風呂の鏡を覗く": "Look into the bathroom mirror",
  "曇った鏡に、自分ではない息の跡が増えている。": "Breath marks cloud the mirror. They aren't mine.",
  "冷蔵庫を開ける": "Open refrigerator",
  "電気は止まっているのに、中が冷えている。": "The power is off, but it is cold inside.",
  "交換用の電池を取る": "Take replacement battery",
  "外へ出る": "Go outside",
  "上る": "Go up",
  "下りる": "Go down",
  "住民各位": "To all residents",
  "夜間の物音について": "Nighttime noises",
  "心当たりのある方は": "If you know anything,",
  "管理人室まで": "contact the caretaker",
  "覗く": "Look inside",
  "４かいは かえれない": "no way back from 4F",
  "——顔が触れる寸前、それは消えた。": "—Just before its face touched mine, it vanished.",
  "秒": " sec",
  "——電池が切れた。懐中電灯は持っている。電池を交換しよう。": "—The battery is dead. I still have the flashlight. I need a replacement battery.",
  "懐中電灯を持っていない。一〇一号室の玄関に置いたままだ。": "I don't have the flashlight. I left it by the entrance to Room 101.",
  "懐中電灯の電池が切れている。この階の部屋で交換用の電池を探そう。": "The flashlight battery is dead. Search the rooms on this floor for a replacement.",
  "電池を入れ替えた。": "Battery replaced.",
  "記録しました（どの端末でも続けられます）": "Saved to the cloud. You can continue on another device.",
  "この端末に記録しました": "Saved on this device.",
  "別の端末に、あとから保存された記録があります。どちらを残しますか。": "Another device has a newer save. Which progress would you like to keep?",
  "この端末の記録を残す": "Keep this device's progress",
  "この端末の記録で上書きしました": "Cloud save replaced with this device's progress.",
  "向こうの記録を読み込む": "Load the other save",
  "この階のどこかの部屋に、交換用の電池がある。部屋の中を探そう。": "There is a replacement battery in a room on this floor. Search inside the rooms.",
  "……廊下を、誰かが通った。": "…Someone passed along the corridor.",
  "——扉が、閉まった。": "—The door closed.",
  "冷蔵庫を閉める": "Close refrigerator",
  "……四〇四号室。名前の札が、無い。": "…Room 404. The nameplate is missing.",
  "鍵がかかっている。人の気配もない。": "It's locked. No sign of anyone inside.",
  "を取りました。": " acquired.",
  "もう入れてある。": "It is already switched on.",
  "階段室に、明かりがついた。": "The stairwell lights came on.",
  "上れない。": "I can't go up.",
  "。（休 → こまったときは、で詳しく）": ". (Pause → Help for details.)",
  "……まだ帰れない。": "…I can't leave yet.",
  "……まだ、上に行かせてもらえない。": "…It won't let me go up yet.",
  "——廊下の灯りが、いっせいに落ちた。": "—Every light in the corridor went out at once.",
  "階段まで。振り返るな。": "Get to the stairs. Don't look back.",
  "ログイン中：": "Logged in: ",
  "この端末だけに記録しています": "Saving on this device only",
  "つづける": "Continue",
  "鬼ごっこをやめる": "Leave multiplayer",
  "音のたしかめ": "Sound check",
  "いま記録する": "Save now",
  "記録しています…": "Saving…",
  "こまったときは（やり方とヒント）": "Help and hints",
  "持ち物とメモ": "Items and notes",
  "友達と遊ぶ（鬼ごっこ）": "Play with friends (Tag)",
  "音を消す": "Mute audio",
  "上下の視点を反転": "Invert vertical look",
  "<span>音の大きさ</span>": "<span>Volume</span>",
  "<span>視点の速さ</span>": "<span>Look sensitivity</span>",
  "アカウントの設定": "Account settings",
  "ログアウト": "Log out",
  "ログアウトしました。この端末の記録は残ります。": "Logged out. Your local save is still on this device.",
  "ログインして、どの端末でも続ける": "Log in to continue on other devices",
  "最初からやり直す": "Start over",
  "いまの記録を消して、最初からやり直しますか。": "Delete your current progress and start from the beginning?",
  "消してやり直す": "Delete and restart",
  "やめる": "Cancel",
  "いま、どうすれば": "What should I do now?",
  "「それ」から逃げるには": "Escaping the Presence",
  "戻る": "Back",
  "このゲームの音は、録音ではなく、その場で作っています。押すと鳴ります。": "The game uses audio recordings and synthesized sounds. Select a sound to preview it.",
  "まだ音を出せていません。いちど画面をさわってから、もう一度開いてください。": "Audio is not ready. Tap the screen once, then open this menu again.",
  "音が出ないときは、端末の音量と、iPhone のマナーモード（消音スイッチ）を確かめてください。": "If you cannot hear anything, check your device volume and your iPhone's silent switch.",
  "名前：": "Name: ",
  "　／　メール：": " / Email: ",
  "登録なし": "Not registered",
  "メールアドレスを登録しておくと、名前を忘れてもログインできます。登録しないままでも、ずっと遊べます。": "An email lets you log in if you forget your name. You can keep playing without one.",
  "いまの合言葉": "Current passphrase",
  "確認のため必要です": "Required for confirmation",
  "メールアドレス": "Email address",
  "変更するときだけ入力": "Enter only to change it",
  "登録するときだけ入力": "Enter only to register it",
  "新しい合言葉": "New passphrase",
  "変えるときだけ入力": "Enter only to change it",
  "いまの合言葉を入れてください。": "Enter your current passphrase.",
  "送っています…": "Sending…",
  "メールアドレスを登録・変更": "Add or change email",
  "メールアドレスを入れてください。": "Enter an email address.",
  "メールアドレスを登録しました。": "Email registered.",
  "メールアドレスを外す": "Remove email",
  "メールアドレスを外しました。": "Email removed.",
  "合言葉を変える": "Change passphrase",
  "新しい合言葉を入れてください。": "Enter a new passphrase.",
  "合言葉を変えました。": "Passphrase changed.",
  "死鏡団地": "Shikyou Danchi",
  "四号棟・解体前夜": "Building Four · The Night Before Demolition",
  "死鏡団地 四号棟。": "Shikyou Danchi. Building Four.",
  "私が十八まで住んでいた建物は、明日の朝、重機に囲まれる。": "The building where I lived until I was eighteen will be surrounded by demolition crews tomorrow morning.",
  "母の部屋に、ノートを一冊置いたままだった。": "I had left a notebook in my mother's room.",
  "電気はもう止まっている。階段で上がるしかない。": "The power is already off. I'll have to take the stairs.",
  "——三十分で戻る。それだけのつもりだった。": "—I'll be back in thirty minutes. That was all I had in mind.",
  "階段室の鉄扉は、押すとまだ動いた。": "The iron stairwell door still moved when I pushed it.",
  "自分の家だったころ、傘立ての上に置いていた。": "When this was home, I kept it above the umbrella stand.",
  "使える電池の入った予備の懐中電灯だ。": "A spare flashlight with a working battery.",
  "解体工事のお知らせ": "Demolition Notice",
  "死鏡団地 四号棟": "Shikyou Danchi · Building Four",
  "八月三十一日をもって": "From August 31 onward",
  "立入を禁止いたします": "No entry permitted",
  "死鏡団地管理組合": "Residents' Association",
  "懐中電灯は、たしか玄関の靴箱の上だ。": "The flashlight should be on the shoe cabinet by the entrance.",
  "……風の音しかしない。": "…Nothing but the wind.",
  "二階": "2F",
  "郵便受けの列が、まだ名前を貼ったまま残っている。": "The row of mailboxes still has all its nameplates.",
  "階段の扉に、南京錠がかかっている。": "There is a padlock on the stairwell door.",
  "台所の壁のフックに、鍵が一本ぶら下がっていた。": "A key hangs from a hook on the kitchen wall.",
  "二〇二号室。あの子の家だ。": "Room 202. That child's home.",
  "——上で、何か落ちた。": "—Something fell upstairs.",
  "扉が、ひとりでに閉まった。": "A door closed by itself.",
  "三階": "3F",
  "蛍光灯が一本だけ、まだ切れかけのまま生きている。": "One fluorescent tube is still flickering, refusing to die.",
  "階段室が暗すぎて、扉の位置さえ分からない。": "The stairwell is too dark. I can't even see the door.",
  "廊下の端の鉄箱。中のつまみが、下がったままだ。": "The metal box at the end of the corridor. The switch inside is still down.",
  "管理人の詰所だった部屋。棚に日誌の切れ端が挟まっている。": "The old caretaker's room. A torn diary page is wedged into a shelf.",
  "……足音が、二重に聞こえる。": "…I can hear two sets of footsteps.",
  "四階": "4F",
  "四階。ここで折り返せば、あと一つ上だ。": "Fourth floor. One more flight after this turn.",
  "……四階。いま、上ったはずだ。": "…Fourth floor. I just went up.",
  "号室の札が、全部同じ数字になっている。": "Every door has the same room number.",
  "四階。四階。四階。": "Fourth floor. Fourth floor. Fourth floor.",
  "一つだけ、扉が開いている。": "Only one door is open.",
  "五階": "5F",
  "五階だけ、廊下の灯りがついていた。": "Only the fifth-floor corridor had its lights on.",
  "自分の家。表札はまだ外されていない。": "My home. The nameplate is still there.",
  "……電気は止まっているはずだ。": "…The power is supposed to be off.",
  "自分の家だったころの部屋。畳の目まで覚えている。": "The room that used to be home. I remember even the weave of the tatami.",
  "靴箱を見る": "Inspect shoe cabinet",
  "傘立ての上。やっぱり、そこにあった。": "Above the umbrella stand. Just where I remembered.",
  "一〇二号室。佐々木さんの家だ。仏間の匂いがまだ残っている。": "Room 102. The Sasakis' home. The smell of the altar room still lingers.",
  "仏壇を見る": "Inspect altar",
  "線香が、途中まで燃えて折れている。灰はまだ温かい。": "An incense stick lies broken, half burned. The ash is still warm.",
  "引っ越しの途中で止まったまま、十何年たった部屋。": "A move that stopped halfway, more than ten years ago.",
  "段ボールを開ける": "Open cardboard box",
  "衣類。いちばん下に、髪の毛が一束、輪ゴムでまとめてある。": "Clothes. At the bottom, a lock of hair tied with a rubber band.",
  "子ども部屋。柱に、背の高さの傷が並んでいる。": "A child's room. Height marks line a wooden pillar.",
  "傷を数える": "Count the marks",
  "十二本ある。最後の一本だけ、天井近くに刻まれている。": "Twelve marks. Only the last is carved close to the ceiling.",
  "からっぽの部屋。家財の跡だけが、畳に焼きついている。": "An empty room. Only the shadows of furniture remain on the tatami.",
  "畳の跡を見る": "Inspect tatami marks",
  "箪笥、卓袱台、それから——人がひとり、ずっと座っていた形。": "A chest of drawers, a low table, and—the shape of someone who sat there for a very long time.",
  "袋の山。中身は分からない。踏むと、やわらかい。": "Piles of bags. I can't tell what's inside. They feel soft underfoot.",
  "袋を見る": "Inspect bags",
  "いちばん上の袋が、いま、ゆっくり沈んだ。": "The topmost bag just sank, slowly.",
  "水回りの部屋。奥の扉の向こうから、水の音がする。": "A washroom. Water is running beyond the door at the back.",
  "風呂の扉を開ける": "Open bathroom door",
  "音が止んだ。浴槽は乾ききっている。髪だけが、排水口から伸びている。": "The sound stopped. The tub is bone dry. Only hair stretches out of the drain.",
  "姿見が三枚、壁に立てかけてある。どれも布がかけてあった形跡がある。": "Three full-length mirrors lean against the wall. Each looks as though it was once covered.",
  "鏡を覗く": "Look into mirror",
  "自分が映っている。……こちらを向くのが、一拍おそい。": "My reflection. …It turns toward me a moment too late.",
  "二〇五号室。高木さんの家。万年床が敷きっぱなしだ。": "Room 205. The Takagis' home. A futon has been left spread out.",
  "布団に触れる": "Touch futon",
  "へこんでいる。人の形に。まだ、温かい。": "An indentation. The shape of a person. Still warm.",
  "三〇一号室。中村さんの家。花瓶がいくつも並んでいる。": "Room 301. The Nakamuras' home. Vases stand in rows.",
  "花瓶を見る": "Inspect vases",
  "花はすべて枯れている。水だけが、新しい。": "Every flower is dead. Only the water is fresh.",
  "物置。家財が天井まで積み上がって、奥へは行けない。": "A storeroom. Furniture is piled to the ceiling, blocking the way.",
  "すきまを覗く": "Look through the gap",
  "奥に、たんすが一棹。その陰から、こちらを見ている。": "A chest of drawers at the back. Something is watching from behind it.",
  "書類棚を見る": "Inspect filing cabinet",
  "住民名簿。八月のところで、名前が一つずつ、線で消されている。": "The residents' register. In August, names have been crossed out one by one.",
  "テレビがついている。電気は止まっているはずだ。": "The television is on. The power is supposed to be off.",
  "画面を見る": "Watch the screen",
  "砂嵐——のあいだに、いま歩いてきた廊下が、一瞬だけ映った。": "Through the static—the corridor I just walked down flashed onto the screen.",
  "子ども部屋。ぬいぐるみが棚に並んでいる。全部、壁を向いている。": "A child's room. Stuffed animals line the shelves. Every one faces the wall.",
  "ぬいぐるみを見る": "Inspect stuffed animals",
  "顔をこちらに直した。……一つだけ、もともとこちらを向いていた。": "I turned their faces toward me. …One had been facing me all along.",
  "何もない。畳だけが、新しく替えられている。": "Nothing here. Only the tatami has been replaced.",
  "畳を見る": "Inspect tatami",
  "四階の畳だけ、どこも新しい。替える必要が、あったのだろうか。": "All the tatami on the fourth floor is new. Why did it need replacing?",
  "段ボールに、几帳面な字で中身が書いてある。": "The contents of each box are written in careful handwriting.",
  "字を読む": "Read the labels",
  "「たいせつなもの」。全部の箱に、同じ字で。": "\"Precious things.\" Every box, in the same handwriting.",
  "壁という壁に、鏡が貼りつけてある。合わせ鏡になっている。": "Mirrors cover every wall, facing each other.",
  "合わせ鏡を覗く": "Look between the mirrors",
  "奥へ、奥へ、自分が続いている。……七番目から、数が合わない。": "My reflections stretch on and on. …After the seventh, the count is wrong.",
  "四〇四号室。表札の枠だけが残っている。": "Room 404. Only the nameplate frame remains.",
  "部屋を見まわす": "Look around the room",
  "誰も住んでいない部屋のはずが、掃除が行き届いている。": "This room should be empty, but someone has kept it spotless.",
  "布団が敷いてある。まんなかが、ふくらんでいる。": "A futon lies spread out. Something bulges beneath the middle.",
  "布団をめくる": "Lift the quilt",
  "何もない。掛け布団の内側だけが、人肌の温度をしている。": "Nothing. Only the underside of the quilt is warm as a body.",
  "花の匂いがする。枯れているのに。": "The flowers smell sweet. Even though they are dead.",
  "花を見る": "Inspect flowers",
  "供花だ。名札に、この棟の号室が書いてある。全部で四つ。": "Funeral flowers. The cards name rooms in this building. Four in all.",
  "がらんとした部屋。窓だけが、きれいに拭いてある。": "A bare room. Only the window has been wiped clean.",
  "窓を見る": "Inspect window",
  "内側から拭いてある。指の跡が、外側にも同じだけ付いている。": "Wiped from inside. The same number of fingerprints mark the outside.",
  "姿見が一枚。ちょうど、玄関を映す向きに置いてある。": "A full-length mirror, placed to reflect the entrance.",
  "鏡を見る": "Inspect mirror",
  "玄関が映っている。いま閉めたはずの扉が、開いている。": "The entrance is reflected. The door I just closed is open.",
  "母が出ていった日のまま。灰皿の上で、線香が一本、燃え尽きている。": "Just as it was when Mother left. A single incense stick has burned out over the ashtray.",
  "仏間。位牌がいくつも並んでいる。数が多すぎる。": "An altar room. Rows of memorial tablets. Far too many.",
  "位牌を数える": "Count memorial tablets",
  "十九。この棟に住んでいた世帯の数と、同じだ。": "Nineteen. The same number of households that lived here.",
  "回覧板の切れ端": "Torn circular notice",
  "一階・掲示板": "1F · Noticeboard",
  "＜解体工事に伴う立入禁止のお知らせ＞": "NO ENTRY — DEMOLITION WORK",
  "八月三十一日をもって、四号棟への立入を": "From August 31, entry to Building Four",
  "全面的に禁止いたします。": "is strictly prohibited.",
  "室内に残された私物につきましては、": "The association accepts no responsibility",
  "当組合では一切の責任を負いかねます。": "for personal belongings left in the building.",
  "なお、四号棟にお住まいの方は": "Please note that the number of households",
  "現在ゼロ世帯となっております。": "currently residing in Building Four is zero.",
  "……この「ゼロ世帯」の上に、": "…Someone has drawn a pencil line",
  "誰かが鉛筆で線を引いて、": "through the words \"zero households\"",
  "「うそ」と書いてある。": "and written \"liar\" above them.",
  "宛名のない葉書": "Unaddressed postcard",
  "二階・郵便受け": "2F · Mailboxes",
  "消印は十二年前。切手は貼られていない。": "The postmark is twelve years old. There is no stamp.",
  "宛名の欄は、まっさらのままだ。": "The address field is completely blank.",
  "　まだ いるのですか": "    are you still there",
  "　こちらは かわりません": "    nothing has changed here",
  "　あかりは つけたままにしてあります": "    we have left the lights on",
  "　かえってくるなら 五かいまで": "    if you come back go to the fifth floor",
  "裏を返すと、鉛筆で薄く": "On the back, written faintly in pencil,",
  "「504」とだけ書いてある。": "are just the numbers \"504.\"",
  "台所のメモ": "Kitchen note",
  "二〇二号室": "Room 202",
  "冷蔵庫に、マグネットで留まっていた。": "It was held to the refrigerator by a magnet.",
  "　・かいだんの かぎ フックにかけた": "    • stair key on the hook",
  "　・よるは でないこと": "    • don't go out at night",
  "　・おとを たてないこと": "    • don't make any noise",
  "三つ目だけ、何度もなぞって書いてある。": "Only the third line has been traced over and over.",
  "管理日誌（切れ端）": "Caretaker's log (fragment)",
  "三〇三号室": "Room 303",
  "八月十四日　晴": "August 14 — Clear",
  "　四号棟、巡回。異常なし。": "    Building Four, routine patrol. Nothing unusual.",
  "八月十七日　曇": "August 17 — Cloudy",
  "　深夜二時、四階で足音の苦情。": "    2 a.m. Complaint about footsteps on the fourth floor.",
  "　行ってみたが誰もいない。": "    Went to check. No one there.",
  "　四階は先月から全戸空き家のはず。": "    Every fourth-floor unit should have been vacant since last month.",
  "八月二十日": "August 20",
  "　五〇四号室の灯りがついている。": "    The lights are on in Room 504.",
  "　電気は先々月に止めたはずだ。": "    The power was supposed to be cut two months ago.",
  "　管理会社に確認するよう申し送る。": "    Ask the management company to check.",
  "八月二十二日": "August 22",
  "　四階から下りられない。": "    Cannot get down from the fourth floor.",
  "　同じ階に出る。四回": "    Keep coming out on the same floor. Four times",
  "（ここで文字が途切れている）": "(The writing ends here.)",
  "壁の落書き": "Graffiti on the wall",
  "四階・廊下": "4F · Corridor",
  "低い位置に、子どもの背丈で書いてある。": "Written low on the wall, at a child's height.",
  "クレヨンが、コンクリートに食い込んでいる。": "The crayon has been pressed deep into the concrete.",
  "　４かいは かえれない": "    no way back from 4F",
  "同じ行が、壁の端まで続いている。": "The same line repeats to the end of the wall.",
  "最後の一行だけ、字が大人のものだ。": "Only the final line is in an adult's handwriting.",
  "　むかえに いきます": "    I will come for you",
  "母の手紙": "Mother's letter",
  "四〇四号室": "Room 404",
  "封も切られていない。宛名は私の名前だ。": "The envelope is unopened. It is addressed to me.",
  "消印は、母が入院した日の少し前だった。": "The postmark is from shortly before Mother went into hospital.",
  "　あなたが小さかったころ、毎朝この廊下を手をつないで歩きました。": "    When you were little, we walked down this corridor hand in hand every morning.",
  "　雨の日に窓から電車を数えたことも、五〇四号室で背を測ったことも、": "    Counting trains through the window on rainy days, measuring your height in Room 504—",
  "　私には、ここで過ごした時間がいちばん大切な宝物です。": "    the time we spent here is my most precious treasure.",
  "　あなたが団地を離れて、自分の暮らしを始めたことをうれしく思っています。": "    I am happy that you left the estate and began a life of your own.",
  "　会いに来られないことを責めないで。病気のことを伝えなかったのは私です。": "    Don't blame yourself for not visiting. I was the one who kept my illness from you.",
  "　元気なあなたの邪魔をしたくありませんでした。": "    I didn't want to stand in the way of your life.",
  "　解体の話を聞いて、せめて思い出の場所だけは守りたいと思いました。": "    When I heard about the demolition, I wanted to protect at least the place that held our memories.",
  "　住民の名前と、この建物であったことをノートに残しています。": "    I am recording the residents' names and what happened here in a notebook.",
  "　建物はなくなっても、あなたが覚えていれば、あの日々はなくなりません。": "    Even if the building disappears, those days will remain as long as you remember them.",
  "　鏡に私のようなものが映っても、私だと思って残らないでください。": "    If something that looks like me appears in a mirror, please don't stay because you think it is me.",
  "　あれは、会えなかったあなたの後悔と、この団地の記憶が作った影です。": "    It is a shadow made from your regret at not seeing me, and the memories of this estate.",
  "　私はあなたを閉じ込めたいのではありません。": "    I don't want to keep you here.",
  "　最後に、会って言いたかったことは一つだけです。": "    There is only one thing I wanted to tell you in person, one last time.",
  "　元気でね。あなたのこれからを、ずっと願っています。": "    Take care of yourself. I will always wish you a good life.",
  "　　　　　　　　　　　　　　母": "                            Mother",
  "母のノート": "Mother's notebook",
  "五〇四号室": "Room 504",
  "表紙に、四号棟の見取り図が描いてある。": "A floor plan of Building Four is drawn on the cover.",
  "住戸の一つ一つに、名前と、退去した日。": "Each home has a name and a moving-out date.",
  "余白には、その家の匂いや、よく聞こえた笑い声まで書かれている。": "In the margins are the smells of those homes, even the laughter she used to hear.",
  "　一〇二　佐々木さん　　三月　　朝に味噌汁の匂い": "    102  The Sasakis — March — Miso soup in the morning",
  "　二〇五　高木さん　　　五月　　雨の日に歌う子": "    205  The Takagis — May — A child singing on rainy days",
  "　三〇一　中村さん　　　七月　　鉢植えを分けてくれた": "    301  The Nakamuras — July — Shared their potted plants",
  "　五〇四　私たち　　　　十八年　息子と暮らした家": "    504  Us — Eighteen years — The home I shared with my son",
  "ページをめくるたび、幼い私の絵や身長の印、母の短い日記が挟まっている。": "Between the pages are childhood drawings, height marks, and short entries from Mother's diary.",
  "母は病室へ移ってからも、管理組合へ何通も手紙を書いていた。": "Even after she moved into the hospital, Mother kept writing to the residents' association.",
  "この団地を残してほしい、と。ここは息子と生きた証だから、と。": "Please save this estate, she wrote. It is proof of the life I shared with my son.",
  "最後のページだけ、文章が途中で途切れている。": "Only the last page ends in an unfinished sentence.",
  "　もう一度会えたら、謝らせず、引き止めず、笑って――": "    If I could see him once more, I wouldn't let him apologize or ask him to stay. I would smile and—",
  "その下に、看護師らしい別の筆跡で一行が添えられている。": "Below it is a line in different handwriting, perhaps a nurse's.",
  "　最期まで、息子さんに『元気でね』と伝えたいと話していました。": "    Until the very end, she said she wanted to tell her son, \"Take care of yourself.\"",
  "懐中電灯。電池はもう長くない。": "A flashlight. The battery won't last much longer.",
  "予備の懐中電灯": "Spare flashlight",
  "電池の入った懐中電灯に持ち替えた。": "Switched to a flashlight with a working battery.",
  "予備の電池": "Spare battery",
  "電池を一本、見つけた。": "Found a battery.",
  "階段の鍵": "Stairwell key",
  "階段の鍵。南京錠のものだ。": "The key to the stairwell padlock.",
  "……おかえり": "…welcome home",
  "……まだ いる": "…still here",
  "……ごう しつ": "…room number",
  "……あかり つけて": "…turn on the light",
  "……よん かい": "…fourth floor",
  "……ふりむかないで": "…don't turn around",
  "……わすれないで": "…don't forget",
  "見られている。": "Something is watching.",
  "走るな。音を立てるな。": "Don't run. Don't make a sound.",
  "扉の中へ。": "Through the door.",
  "近い。": "Close.",
  "肩に、手が触れた。": "A hand touched my shoulder.",
  "冷たくはなかった。子どものころ、母とつないだ手の温度だった。": "It wasn't cold. It was the warmth of Mother's hand when I was a child.",
  "会えないまま母を亡くした私は、その手を離せなかった。": "I had lost her without seeing her again. I couldn't let go of that hand.",
  "鏡の影は母の顔で、『行かないで』と私の後悔を繰り返す。": "The shadow in the mirror wore Mother's face. \"Don't go,\" it said, repeating my own regret.",
  "けれど、それは母が言いたかった言葉ではない。": "But those were not the words she had wanted to say.",
  "郵便受けに私の名前の札が戻り、四〇四号室の扉が閉じた。": "My name returned to a mailbox, and the door to Room 404 closed.",
  "母が外で生きることを願ったと知らないまま、私は思い出の中に残った。": "Not knowing that Mother wanted me to live outside, I stayed behind in the memories.",
  "外": "Outside",
  "団地の玄関を抜けると、夜明け前の風が頬に触れた。": "As I stepped out of the building, the wind before dawn brushed my cheek.",
  "背後で、濡れた裸足の音が敷居の内側で止まった。": "Behind me, the sound of wet bare feet stopped just inside the threshold.",
  "振り返ると、四号棟はただの古い建物だった。": "When I looked back, Building Four was only an old building.",
  "母が守ろうとした場所を、私はまだ思い出しきれない。": "I still couldn't fully remember the place Mother had tried to protect.",
  "それでも鞄のノートを抱き、前を向いて歩いた。": "Even so, I held the notebook in my bag and walked on.",
  "五〇四号室の灯りが二度またたく。": "The light in Room 504 flickered twice.",
  "風にまぎれて、聞き取れないほど小さな母の声がした。": "Lost in the wind, Mother's voice was almost too faint to hear.",
  "——三か月後、建物はなくなった。": "—Three months later, the building was gone.",
  "更地の前で、私はようやく母の名前を声に出した。": "Standing before the empty lot, I finally said Mother's name aloud.",
  "おぼえている": "I remember",
  "団地の玄関を抜ける。空は、夜と朝のあいだの色をしていた。": "I stepped out of the building. The sky was caught between night and morning.",
  "外へ出た瞬間、追ってきた足音が敷居の内側で止まった。": "The moment I left, the footsteps pursuing me stopped just inside the threshold.",
  "ガラス戸に『それ』が映る。母の顔で、私を団地へ引き戻そうとしていた。": "The Presence appeared in the glass door. Wearing Mother's face, it tried to draw me back inside.",
  "でも、あれは母ではない。会えなかった後悔と、失われる場所への恐れだ。": "But it wasn't Mother. It was my regret at not seeing her, and my fear of losing this place.",
  "母は、この団地に私を閉じ込めようとしたのではなかった。": "Mother had never wanted to imprison me in this estate.",
  "私と過ごした日々が消えないように、たった一人で守ろうとしていたのだ。": "She had tried, all alone, to keep the days we shared from disappearing.",
  "幼い私と母が手をつないで階段を降りる記憶が、朝の窓に重なった。": "In the morning window, I saw a memory of us descending the stairs, hand in hand.",
  "『いってらっしゃい』": "\"Have a good day.\"",
  "その声に、私は初めて前を向いたまま答えた。": "For the first time, I answered without looking back.",
  "『行ってきます』": "\"I'll be going, then.\"",
  "五〇四号室の灯りが、二度またたいて消えた。": "The light in Room 504 flickered twice, then went out.",
  "『それ』の顔から母の面影がほどけ、暗い玄関の奥へ消えていった。": "Mother's features unraveled from the Presence's face, and it vanished into the dark entrance.",
  "——建物は、夏の終わりになくなった。": "—The building was demolished at the end of summer.",
  "私はノートを開き、団地で母と笑った日のことを書き続けている。": "I still open the notebook and write about the days Mother and I laughed together here.",
  "場所はなくなっても、母が守りたかった時間は、私の中に残っている。": "The place is gone, but the time she wanted to protect lives on inside me.",
  "最後のページに、病室の母が託した本当の言葉がある。": "On the last page are the words Mother truly left for me from her hospital bed.",
  "『元気でね』": "\"Take care of yourself.\"",
  "私は泣きながら笑って、朝の道を歩き出した。": "Crying and smiling, I set off down the morning road.",
  "階段室の外扉を調べ、団地の外へ出ます。": "Inspect the outer stairwell door and leave the estate.",
  "懐中電灯を拾う": "Find the flashlight",
  "一〇一号室の扉を開けて、中に入ります。": "Open the door to Room 101 and go inside.",
  "玄関を入ってすぐ右、靴箱の上に置いてあります。": "It is on the shoe cabinet immediately to your right as you enter.",
  "拾ったら、階段室へ戻って「上る」。": "Once you have it, return to the stairwell and choose \"Go up.\"",
  "二階へ上がる": "Go to the second floor",
  "廊下の左端が階段室です。中で「上る」を選びます。": "The stairwell is at the left end of the corridor. Choose \"Go up\" inside.",
  "階段の鍵を探す": "Find the stairwell key",
  "階段の扉に南京錠がかかっています。": "The stairwell door is padlocked.",
  "鍵は 二〇二号室 の台所、壁のフックにぶら下がっています。": "The key hangs from a hook on the kitchen wall in Room 202.",
  "二〇二号室は、階段室から二番目の扉です。": "Room 202 is the second door from the stairwell.",
  "三階へ上がる": "Go to the third floor",
  "鍵は持っています。階段室へ戻って「上る」。": "You have the key. Return to the stairwell and choose \"Go up.\"",
  "分電盤のつまみを上げる": "Raise the circuit breaker switch",
  "階段室が暗すぎて、扉の位置が分かりません。": "The stairwell is too dark to see the door.",
  "廊下を いちばん奥（階段室と反対の端）まで歩くと、": "Walk to the far end of the corridor, opposite the stairwell.",
  "壁に灰色の鉄の箱が付いています。それが分電盤です。": "The gray metal box on the wall is the circuit breaker.",
  "近づいて「開ける」を選ぶと、明かりがつきます。": "Approach it and choose \"Open\" to turn on the lights.",
  "※この階には「それ」がいます。出会ったら、": "The Presence is on this floor. If you meet it,",
  "　まんなかを避けて、どちらかの壁ぎわに寄ってください。": "    stay out of the middle and move close to either side wall.",
  "　寄ればすれ違えます。正面から向かうとつかまります。": "    You can slip past at the edge. A head-on approach gets you caught.",
  "　開いている扉に飛び込んでも助かります。": "    You can also escape into an open room.",
  "四階へ上がる": "Go to the fourth floor",
  "明かりはつきました。階段室へ戻って「上る」。": "The lights are on. Return to the stairwell and choose \"Go up.\"",
  "つまみを上げた音で「それ」が寄ってきています。": "The sound of the switch has drawn the Presence toward you.",
  "危なくなったら、開いている住戸へ飛び込んでください。": "If you are in danger, run into an open apartment.",
  "四階から抜け出す": "Escape the fourth floor",
  "上っても、また四階に出ます。それでかまいません。": "Going up brings you back to the fourth floor. That's expected.",
  "二度、上ってください。三度目の四階は廊下が短く、": "Go up twice. The third version of the fourth floor has a shorter corridor",
  "扉がひとつだけ開いています。": "and only one open door.",
  "その部屋の文机にある「母の手紙」を読むと、抜けられます。": "Read Mother's letter on the writing desk in that room to escape the loop.",
  "五階へ上がる": "Go to the fifth floor",
  "手紙は読みました。階段室から「上る」。": "You have read the letter. Choose \"Go up\" in the stairwell.",
  "母のノートを取る": "Take Mother's notebook",
  "五〇四号室に入ります。階段室から四番目の扉です。": "Enter Room 504, the fourth door from the stairwell.",
  "いちばん奥の部屋、机の上にノートがあります。": "The notebook is on the desk in the room furthest inside.",
  "取ったら、廊下の照明が全部落ちます。走って階段室へ。": "Taking it puts out every corridor light. Run to the stairs.",
  "階段室で「下りる」を選び、一階まで降りて外へ。": "Choose \"Go down\" in the stairwell. Keep descending to the first floor, then leave.",
  "階段室へ": "Get to the stairs",
  "廊下の左端が階段室です。": "The stairwell is at the left end of the corridor.",
  "正面から向かっていくと、必ずつかまる": "A head-on approach gets you caught",
  "廊下の幅は2.55m。まんなかを進むとぶつかります。扉側か手すり側の、どちらかの壁ぎわに寄ってください。寄れば、すれ違って逃げられます。": "The corridor is 2.55 meters wide. Stay close to the doors or the railing instead of the middle. You can slip past along either edge.",
  "住戸の中と階段室には入ってこない": "Apartments and stairwells offer shelter",
  "「それ」が出る階では、はじめから開いている扉がいくつかあります。飛び込めば助かります。中にいるあいだは追ってきません。": "Some doors start open on floors where the Presence appears. Escape inside; it won't follow into an apartment. During the final escape, it does follow you down the stairs.",
  "走ると、足音でまず見つかる": "Running gives away your position",
  "走る＞歩く＞しゃがむ の順に響きます。近くにいるときは、しゃがんで動いてください。": "Running is loudest, then walking, then crouching. Crouch when it is nearby.",
  "懐中電灯は、見つかる元でもある": "Your flashlight can give you away",
  "遠くからでも光が見えます。危ないと思ったら消してください（灯／F キー）。": "Its beam can be seen from far away. Turn it off if you feel threatened (Light / F).",
  "正面から光を当てると、一瞬止まる": "A direct beam stops it briefly",
  "そのすきに逃げられます。ただし何度も効きません。止まったあとは速くなります。": "Use that moment to escape. This does not work repeatedly, and it moves faster afterward.",
  "心臓の音が速くなったら、近い": "The screen warns you when danger is close",
  "画面のふちが暗く赤くなり、すぐ後ろにいると息づかいが聞こえます。": "The edges of the screen grow dark and red as danger approaches.",
  "つかまっても、その階の最初からやり直せる": "If caught, retry from the start of that floor",
  "進み具合（メモや持ち物）は消えません。": "Your collected notes and items are kept.",
  "ひとりでに起きることは、こわいだけで害はない": "Unexplained events are frightening but harmless",
  "鍋が落ちる、扉が揺れる、勝手に開く、灯りが消えてまた点く、壁に血が滲む、無かったはずの靴が落ちている——どれも触ってきません。「それ」とは別のものです。おどろいて走ると、かえって足音で見つかります。": "Falling pots, shaking doors, lights going out, blood seeping through walls, shoes that weren't there before—none can touch you. They are separate from the Presence. Running in panic may give you away.",
  "移動": "Move",
  "マウス": "Mouse",
  "見まわす": "Look around",
  "走る（音が響く）": "Run (noisy)",
  "しゃがむ（静かに歩く）": "Crouch (quiet)",
  "E / クリック": "E / Click",
  "調べる・開ける": "Inspect / Open",
  "ポーズ": "Pause",
  "左スティック": "Left stick",
  "画面を なぞる": "Drag the screen",
  "調": "Use",
  "走": "Run",
  "走る": "Run",
  "屈": "Crouch",
  "しゃがむ": "Crouch",
  "灯": "Light",
  "帳": "Notes",
  "持ち物": "Inventory",
  "<p class=\"dim\">なにも持っていない。</p>": "<p class=\"dim\">You aren't carrying anything.</p>",
  "・": "•",
  "見つけたもの　": "Found: ",
  "操作": "Controls",
  "<div>見つけたもの　": "<div>Found: ",
  "<div>かかった時間　": "<div>Time: ",
  "もう一度": "Play again",
  "はじめての方へ · {0}/2": "Quick guide · {0}/2",
  "<ol><li>Safariでこのゲームを開きます。</li><li><span class=\"welcome-phrase\">共有ボタンを押します。</span><br><span class=\"welcome-phrase\">四角から上向き矢印の</span><span class=\"welcome-phrase\">マークです。</span><br><span class=\"welcome-phrase\">見当たらないときは</span><span class=\"welcome-phrase\">メニュー内を確認します。</span></li><li><span class=\"welcome-phrase\">「ホーム画面に追加」</span>を選び、<span class=\"welcome-phrase\">「追加」を押します。</span><br><span class=\"welcome-phrase\">「Webアプリとして開く」</span><span class=\"welcome-phrase\">が表示されたら</span><span class=\"welcome-phrase\">オンにします。</span></li></ol>": "<ol><li>Open the game in Safari.</li><li>Tap Share (the square with an upward arrow). If it is hidden, look in the browser menu.</li><li>Choose “Add to Home Screen”, then “Add”. If “Open as Web App” appears, turn it on.</li></ol>",
  "<ol><li>Chromeでこのゲームを開きます。</li><li>右上の「⋮」メニューを開きます。</li><li><span class=\"welcome-phrase\">「ホーム画面に追加」</span>を選びます。表示が異なる場合は「インストールしてショートカットを作成」を選び、案内に沿って追加します。</li></ol>": "<ol><li>Open the game in Chrome.</li><li>Open the ⋮ menu at the top right.</li><li>Choose “Add to Home screen” or the option to install or create a shortcut, then follow the prompts.</li></ol>",
  "<ol><li>ChromeまたはEdgeでこのゲームを開きます。</li><li>ブラウザーのメニューから、アプリのインストールやショートカットの作成を選びます。</li><li>画面の案内に沿って追加します。</li></ol>": "<ol><li>Open the game in Chrome or Edge.</li><li>In the browser menu, choose the option to install the app or create a shortcut.</li><li>Follow the prompts to finish.</li></ol>",
  "<strong>ホーム画面から起動できています</strong><p>追加の操作は必要ありません。そのまま遊べます。</p>": "<strong>Already running from your home screen</strong><p>You're all set. No further steps are needed.</p>",
  "追加されました。次からはホーム画面のアイコンから開けます。": "Added. Next time, open the game from its home screen icon.",
  "追加手続きを受け付けました。端末の案内をご確認ください。": "Installation was requested. Please follow your device's prompts.",
  "追加はあとからでもできます。上の手順からお試しください。": "You can add it later using the steps above.",
  "上のブラウザーのメニュー操作で追加できます。": "Use the browser menu and follow the steps above to add the game.",
  "電池": "Battery",
  "休": "Pause",
  "閉じる": "Close",
  "手帳": "Notebook",
  "小休止": "Pause",
  "記録が二つあります": "Two saved games",
  "この端末とクラウドで、進み具合が違います。どちらで続けますか。": "Your local and cloud saves differ. Which would you like to continue?",
  "この端末": "This device",
  "この端末の記録で続ける": "Continue local save",
  "クラウド": "Cloud",
  "クラウドの記録で続ける": "Continue cloud save",
  "鬼ごっこ": "Multiplayer Tag",
  "2〜4人。ひとりが「それ」になり、残りは鍵を三本あつめて階段室から逃げます。": "2–4 players. One becomes the Presence. The others collect three keys and escape through the stairwell.",
  "どの階で遊ぶか": "Choose a floor",
  "部屋をつくる": "Create room",
  "友達の合言葉を入れる": "Enter your friend's room code",
  "その部屋に入る": "Join room",
  "この合言葉を、友達に伝えてください。": "Share this room code with your friends.",
  "友達がつながると、ここに名前が出ます。": "Your friends' names will appear here when they connect.",
  "部屋を作った人が審判をします。その人の画面を裏にすると、みんなの進行が止まります。": "The host runs the game. Switching away from the game pauses play for everyone.",
  "ログインしておくと、パソコンでもスマホでも、同じところから続きを遊べます。": "Log in to continue your saved game on a computer or phone.",
  "メールアドレスは入れても入れなくてもかまいません。": "An email address is optional.",
  "「": "Continue as ",
  "」で続ける": "",
  "はじめて": "Sign up",
  "この端末だけ": "Guest",
  "名前　または　メールアドレス": "Name or email address",
  "かえで　または　you@example.com": "Your name or you@example.com",
  "名前（ログインに使います）": "Name (used to log in)",
  "2〜16文字・空白なし": "2–16 characters, no spaces",
  "ローマ字でも、ひらがなでもかまいません。": "You can use English or Japanese characters.",
  "合言葉": "Passphrase",
  "4文字以上": "At least 4 characters",
  "メールアドレス（任意）": "Email address (optional)",
  "空のままでも登録できます": "You can leave this blank",
  "入れておくと、名前を忘れてもメールでログインできます。あとから登録・削除もできます。": "Use an email to log in if you forget your name. You can add or remove it later.",
  "この端末の中だけに記録を残します。ほかの機械には引き継げません。": "Progress is saved only on this device and cannot be accessed elsewhere.",
  "あとからログインすれば、そのときの進み具合をそのまま預けられます。": "Log in later to upload your local progress to the cloud.",
  "ログインしないで遊ぶ": "Play without logging in",
  "ヘッドホンと、暗い部屋をおすすめします。": "Headphones and a dark room are recommended.",
  "スマートフォンは、横向きにすると見やすくなります。": "On phones, landscape orientation gives a wider view.",
  "名前は2〜16文字。空白と @ は使えません。": "Names must be 2–16 characters, without spaces or @.",
  "その名前は使われています。": "That name is already taken.",
  "この名前は使えます。": "That name is available.",
  "メールアドレスの形式が違います。": "Enter a valid email address.",
  "その名前はすでに使われています。": "That name is already taken.",
  "そのメールアドレスはすでに使われています。": "That email address is already registered.",
  "名前（またはメール）と合言葉を入力してください。": "Enter your name (or email) and passphrase.",
  "名前か合言葉が違います。": "Incorrect name or passphrase.",
  "不明な操作です。": "Unknown action.",
  "サーバーに接続できませんでした。": "Could not connect to the server.",
  "ログインし直してください。": "Please log in again.",
  "アカウントが見つかりませんでした。": "Account not found.",
  "今の合言葉が違います。": "The current passphrase is incorrect.",
  "名前を入力してください。": "Enter a name.",
  "記録の中身がありません。": "No save data was provided.",
  "記録が大きすぎます。": "The save data is too large.",
  "別の端末に新しい記録があります。": "Another device has a newer save.",
  "サーバーの準備がまだです。『この端末だけ』で遊べます。": "The server is not ready. You can still play as a guest on this device.",
  "いま混み合っています。少し待ってください。": "The server is busy. Please try again shortly.",
  "その部屋は見つかりません。": "Room not found.",
  "その部屋は時間切れです。作り直してください。": "That room has expired. Please create a new room.",
  "その部屋は、もう始まっています。": "The game in that room has already started.",
  "部屋がいっぱいです。": "The room is full.",
  "通信に失敗しました。": "Connection failed.",
  "はじめての方へ · 1/2": "Quick guide · 1/2",
  "はじめての方へ · 2/2": "Quick guide · 2/2",
  "スキップ": "Skip",
  "案内を閉じる": "Close guide",
  "続きを守る、": "Keep your progress.",
  "かんたんログイン": "Log in with ease.",
  "はじめる前に、": "Before you begin, ",
  "名前と合言葉を": "choose a name and passphrase ",
  "登録しませんか？": "to create an account.",
  "メールアドレスは不要です": "No email address needed",
  "好きな名前と、": "You only need a name ",
  "4文字以上の合言葉だけで": "and a passphrase of at least 4 characters ",
  "登録できます。": "to sign up.",
  "進み具合を": "Your progress ",
  "クラウドに保存できます。": "can be saved to the cloud.",
  "端末のデータが消えても、": "Even if your device's data is lost, ",
  "同じ名前と合言葉で": "use the same name and passphrase ",
  "保存した続きから遊べます。": "to continue from your cloud save.",
  "保存には通信が必要です。": "Saving requires an internet connection. ",
  "名前と合言葉は": "Keep your name and passphrase ",
  "控えておいてください。": "somewhere safe.",
  "次へ：ホーム画面に追加": "Next: Add to Home Screen",
  "次からは、": "One tap",
  "ホーム画面から": "to return.",
  "ホーム画面に追加すると、": "Add the game to your home screen ",
  "アイコンを押すだけで": "to open it directly ",
  "すぐに遊べます。": "from its icon.",
  "お使いの端末": "Your device",
  "ホーム画面に追加する": "Add to Home Screen",
  "追加はあとからでもできます。": "You can add it later. ",
  "ログインしてください。": "to log in.",
  "名前と合言葉を登録する": "Create your account",
  "Safariでこのゲームを開きます。": "Open this game in Safari.",
  "共有ボタンを押します。": "Tap the Share button.",
  "四角から上向き矢印の": "Look for a square ",
  "マークです。": "with an upward arrow.",
  "見当たらないときは": "If it is hidden, ",
  "メニュー内を確認します。": "look in the browser menu.",
  "「ホーム画面に追加」": "“Add to Home Screen”",
  "を選び、": ", then select ",
  "「追加」を押します。": "“Add”.",
  "「Webアプリとして開く」": "“Open as Web App”",
  "が表示されたら": ": if this option appears, ",
  "オンにします。": "turn it on.",
  "Chromeでこのゲームを開きます。": "Open this game in Chrome.",
  "右上の「⋮」メニューを開きます。": "Open the ⋮ menu at the top right.",
  "を選びます。表示が異なる場合は「インストールしてショートカットを作成」を選び、案内に沿って追加します。": ". If the label differs, choose the install or shortcut option and follow the prompts.",
  "ChromeまたはEdgeでこのゲームを開きます。": "Open this game in Chrome or Edge.",
  "ブラウザーのメニューから、アプリのインストールやショートカットの作成を選びます。": "In the browser menu, choose the option to install the app or create a shortcut.",
  "画面の案内に沿って追加します。": "Follow the prompts to finish.",
  "ホーム画面から起動できています": "Already running from your home screen",
  "追加の操作は必要ありません。そのまま遊べます。": "You're all set. No further steps are needed.",
  "なにも持っていない。": "You aren't carrying anything.",
  "かかった時間": "Time",
  "音の大きさ": "Volume",
  "視点の速さ": "Look sensitivity"
};
