// Spanish display strings. Save IDs and story logic are unchanged.
export const ES = {
  "サーバーに接続できませんでした。通信の状態を確かめてください。": "No se pudo conectar con el servidor. Comprueba tu conexión.",
  "サーバー機能が見つかりません。公開URLで開いてください。": "Las funciones del servidor no están disponibles aquí. Abre la dirección pública del juego.",
  "うまくいきませんでした（": "Se ha producido un error (",
  "階": "P",
  "八月": "Agosto",
  "かぞく": "familia",
  "ログイン": "Iniciar sesión",
  "はじめる": "Comenzar",
  "この端末で はじめる": "Jugar en este dispositivo",
  "名前（またはメール）と合言葉を入れてください。": "Introduce tu nombre (o correo) y contraseña.",
  "確かめています…": "Comprobando…",
  "名前を入れてください。": "Introduce un nombre.",
  "合言葉は4文字以上にしてください。": "La contraseña debe tener al menos 4 caracteres.",
  "登録しています…": "Creando cuenta…",
  "はじめから": "Desde el principio",
  "一階": "Planta 1",
  "　／　見つけたもの ": " / Hallazgos: ",
  "分": " min",
  "記録を読んでいます…": "Cargando partida…",
  "この端末の記録を、クラウドに預けました。": "Tu progreso local se ha guardado en la nube.",
  "この端末では画面を描き始められませんでした。ブラウザを新しくするか、別の端末でお試しください。（": "No se pudo iniciar la imagen del juego. Actualiza el navegador o prueba otro dispositivo. (",
  "原因不明": "Causa desconocida",
  "ログインしました。どの端末でも続けられます。": "Has iniciado sesión. Puedes continuar en otro dispositivo.",
  "📱 この端末だけ": "Solo este dispositivo",
  "ログイン中": "Sesión iniciada",
  "ログインしていません": "Sin iniciar sesión",
  "プレイヤー": "Jugador",
  "部屋の主": "Anfitrión",
  "中継でつながった": "Conexión mediante retransmisión",
  "つながった": "Conectado",
  "つないでいます…": "Conectando…",
  "友達を待っています…": "Esperando a tus amigos…",
  "はじめる（": "Comenzar (",
  "人）": " jugadores)",
  "部屋の主が始めるのを待っています…": "Esperando a que el anfitrión comience…",
  "部屋をつくっています…": "Creando sala…",
  "で遊びます": " seleccionado",
  "合言葉は4文字です。": "El código de la sala debe tener 4 caracteres.",
  "その部屋を探しています…": "Buscando la sala…",
  "つながりました。部屋の主が始めるのを待ちましょう。": "Conectado. Esperando a que el anfitrión comience.",
  " さん、おかえりなさい。": ", te damos la bienvenida de nuevo.",
  "ホスト": "Anfitrión",
  "つながりませんでした。通信の状態を確かめてください。": "No se pudo conectar. Comprueba tu conexión.",
  "——台所で、鍋が落ちた。": "—Se ha caído una olla en la cocina.",
  "……さっきまで、こんな靴は無かった。": "…Esos zapatos no estaban aquí hace un momento.",
  "……壁が、濡れている。": "…La pared está mojada.",
  "……どこかの扉が、揺れている。": "…En algún lugar, una puerta tiembla.",
  "閉める": "Cerrar",
  "開ける": "Abrir",
  "……閉まったままの扉の下から、灯りが漏れている。": "…Se filtra luz por debajo de una puerta cerrada.",
  "それ": "La Presencia",
  "住人": "Residente",
  "住人を全員つかまえろ。音の波紋が見える。": "Atrapa a todos los residentes. Puedes ver las ondas que producen sus sonidos.",
  "鍵を三本あつめて、階段室から出る。走れば聞かれる。": "Reúne tres llaves y escapa por la escalera. Se te oye cuando corres.",
  "だれか": "Alguien",
  "つかまった。仲間が来るまで動けない。": "Te han atrapado. Espera a que un compañero te rescate.",
  " がつかまった。": " ha caído en sus garras.",
  "助けてもらった。": "Te han rescatado.",
  " が起きあがった。": " se ha levantado.",
  "……連れて行かれた。": "…Se lo han llevado.",
  " が連れて行かれた。": " ha desaparecido en sus garras.",
  "鍵 ": "Llaves ",
  "　階段室へ！": " — ¡Ve a la escalera!",
  "時間切れ": "Se acabó el tiempo",
  "全員つかまった": "Todos han sido atrapados",
  "逃げきった": "Has escapado",
  "夜が明けはじめた。": "Empieza a amanecer.",
  "廊下に、誰の姿もない。": "Ya no queda nadie en el pasillo.",
  "郵便受けの札が、一枚ずつ増えている。": "En los buzones aparecen placas con nombres, una tras otra.",
  "廊下の照明が、一本ずつ点いていく。": "Las luces del pasillo se encienden una a una.",
  "郵便受けに、名前の札が増えている。": "Aparece otra placa con un nombre en un buzón.",
  "鉄扉を押し開けて、外に出た。": "Empujé la puerta de hierro y salí al exterior.",
  "うしろで、扉が閉まる音がした。": "A mi espalda, oí cerrarse la puerta.",
  "　——勝ち": " — VICTORIA",
  "　——負け": " — DERROTA",
  "　のこり ": " — Quedan: ",
  "人": " jugadores",
  "　鍵 ": " / Llaves ",
  "　あと": " / Faltan: ",
  "回": " veces",
  "音声を取得できません: {0}": "No se pudo cargar el audio: {0}",
  "突然の出現（Sudden Terror）": "Aparición repentina (Sudden Terror)",
  "足音（歩く）": "Pasos al caminar",
  "足音（走る）": "Pasos al correr",
  "足音（しゃがむ）": "Pasos en cuclillas",
  "階段": "Escaleras",
  "扉を開ける": "Abrir puerta",
  "扉を閉める": "Cerrar puerta",
  "鍵がかかっている": "Puerta cerrada con llave",
  "扉が勢いよく閉まる": "Portazo",
  "紙をめくる": "Pasar páginas",
  "引き出し・押し入れ": "Cajón / armario",
  "袋がこすれる": "Crujido de una bolsa",
  "床がきしむ": "Crujido del suelo",
  "鍋が落ちる": "Caída de una olla",
  "拾う": "Recoger",
  "懐中電灯": "Linterna",
  "分電盤のつまみ": "Interruptor del cuadro eléctrico",
  "水が一滴": "Gota de agua",
  "蛍光灯が切れる": "Tubo fluorescente que se apaga",
  "外廊下の風": "Viento en el pasillo",
  "遠くの物音": "Ruido lejano",
  "戸を叩く音": "Golpes en una puerta",
  "廊下を通る足音": "Pasos por el pasillo",
  "裸足でついてくる": "Pies descalzos que te siguen",
  "濡れた服を引きずる": "Ropa mojada arrastrándose",
  "冷蔵庫の内側": "Interior del frigorífico",
  "品物": "Objeto",
  "を取る": " — Recoger",
  "読む": "Leer",
  "手に取る": "Recoger",
  "調べる": "Examinar",
  "を開ける": " — Abrir",
  "トイレ": "Aseo",
  "風呂": "Baño",
  "トイレの鏡を覗く": "Mirar el espejo del aseo",
  "風呂の鏡を覗く": "Mirar el espejo del baño",
  "曇った鏡に、自分ではない息の跡が増えている。": "El espejo se empaña con un aliento que no es el mío.",
  "冷蔵庫を開ける": "Abrir frigorífico",
  "電気は止まっているのに、中が冷えている。": "No hay electricidad, pero por dentro está frío.",
  "交換用の電池を取る": "Recoger pila de repuesto",
  "外へ出る": "Salir",
  "上る": "Subir",
  "下りる": "Bajar",
  "住民各位": "A todos los residentes",
  "夜間の物音について": "Ruidos nocturnos",
  "心当たりのある方は": "Si saben algo,",
  "管理人室まで": "avisen al conserje",
  "覗く": "Mirar dentro",
  "４かいは かえれない": "de la planta 4 no se vuelve",
  "——顔が触れる寸前、それは消えた。": "—Desapareció justo antes de que su rostro rozara el mío.",
  "秒": " s",
  "——電池が切れた。懐中電灯は持っている。電池を交換しよう。": "—La pila se ha agotado. Aún tengo la linterna. Necesito cambiar la pila.",
  "懐中電灯を持っていない。一〇一号室の玄関に置いたままだ。": "No tengo la linterna. La dejé en la entrada del piso 101.",
  "懐中電灯の電池が切れている。この階の部屋で交換用の電池を探そう。": "La pila de la linterna se ha agotado. Busca un repuesto en los pisos de esta planta.",
  "電池を入れ替えた。": "Pila cambiada.",
  "記録しました（どの端末でも続けられます）": "Guardado en la nube. Puedes continuar en otro dispositivo.",
  "この端末に記録しました": "Guardado en este dispositivo.",
  "別の端末に、あとから保存された記録があります。どちらを残しますか。": "Hay una partida más reciente en otro dispositivo. ¿Qué progreso quieres conservar?",
  "この端末の記録を残す": "Conservar el progreso de este dispositivo",
  "この端末の記録で上書きしました": "La partida en la nube se ha sustituido por la de este dispositivo.",
  "向こうの記録を読み込む": "Cargar la otra partida",
  "この階のどこかの部屋に、交換用の電池がある。部屋の中を探そう。": "Hay una pila de repuesto en algún piso de esta planta. Busca dentro de los pisos.",
  "……廊下を、誰かが通った。": "…Alguien ha pasado por el pasillo.",
  "——扉が、閉まった。": "—La puerta se ha cerrado.",
  "冷蔵庫を閉める": "Cerrar frigorífico",
  "……四〇四号室。名前の札が、無い。": "…Piso 404. Falta la placa con el nombre.",
  "鍵がかかっている。人の気配もない。": "Está cerrado con llave. No parece haber nadie dentro.",
  "を取りました。": " adquirido.",
  "もう入れてある。": "Ya está encendido.",
  "階段室に、明かりがついた。": "Las luces de la escalera se han encendido.",
  "上れない。": "No puedo subir.",
  "。（休 → こまったときは、で詳しく）": ". (Más información en Pausa → Ayuda.)",
  "……まだ帰れない。": "…Aún no puedo irme.",
  "……まだ、上に行かせてもらえない。": "…Aún no me deja subir.",
  "——廊下の灯りが、いっせいに落ちた。": "—Todas las luces del pasillo se apagaron a la vez.",
  "階段まで。振り返るな。": "Ve a la escalera. No mires atrás.",
  "ログイン中：": "Sesión iniciada: ",
  "この端末だけに記録しています": "Guardando solo en este dispositivo",
  "つづける": "Continuar",
  "鬼ごっこをやめる": "Salir del multijugador",
  "音のたしかめ": "Probar sonidos",
  "いま記録する": "Guardar ahora",
  "記録しています…": "Guardando…",
  "こまったときは（やり方とヒント）": "Ayuda y pistas",
  "持ち物とメモ": "Objetos y notas",
  "友達と遊ぶ（鬼ごっこ）": "Jugar con amigos (Persecución)",
  "音を消す": "Silenciar audio",
  "上下の視点を反転": "Invertir vista vertical",
  "<span>音の大きさ</span>": "<span>Volumen</span>",
  "<span>視点の速さ</span>": "<span>Sensibilidad de la vista</span>",
  "アカウントの設定": "Ajustes de la cuenta",
  "ログアウト": "Cerrar sesión",
  "ログアウトしました。この端末の記録は残ります。": "Sesión cerrada. Tu partida local sigue en este dispositivo.",
  "ログインして、どの端末でも続ける": "Inicia sesión para continuar en otros dispositivos",
  "最初からやり直す": "Volver a empezar",
  "いまの記録を消して、最初からやり直しますか。": "¿Borrar tu progreso actual y empezar desde el principio?",
  "消してやり直す": "Borrar y reiniciar",
  "やめる": "Cancelar",
  "いま、どうすれば": "¿Qué hago ahora?",
  "「それ」から逃げるには": "Cómo escapar de la Presencia",
  "戻る": "Volver",
  "このゲームの音は、録音ではなく、その場で作っています。押すと鳴ります。": "El juego usa grabaciones y sonidos sintetizados. Selecciona un sonido para escucharlo.",
  "まだ音を出せていません。いちど画面をさわってから、もう一度開いてください。": "El audio aún no está listo. Toca la pantalla y vuelve a abrir este menú.",
  "音が出ないときは、端末の音量と、iPhone のマナーモード（消音スイッチ）を確かめてください。": "Si no oyes nada, comprueba el volumen del dispositivo y el interruptor de silencio del iPhone.",
  "名前：": "Nombre: ",
  "　／　メール：": " / Correo: ",
  "登録なし": "Sin registrar",
  "メールアドレスを登録しておくと、名前を忘れてもログインできます。登録しないままでも、ずっと遊べます。": "Un correo te permite iniciar sesión si olvidas tu nombre. Puedes seguir jugando sin añadirlo.",
  "いまの合言葉": "Contraseña actual",
  "確認のため必要です": "Necesaria para confirmar",
  "メールアドレス": "Correo electrónico",
  "変更するときだけ入力": "Rellena solo para cambiarlo",
  "登録するときだけ入力": "Rellena solo para registrarlo",
  "新しい合言葉": "Nueva contraseña",
  "変えるときだけ入力": "Rellena solo para cambiarla",
  "いまの合言葉を入れてください。": "Introduce tu contraseña actual.",
  "送っています…": "Enviando…",
  "メールアドレスを登録・変更": "Añadir o cambiar correo",
  "メールアドレスを入れてください。": "Introduce un correo electrónico.",
  "メールアドレスを登録しました。": "Correo registrado.",
  "メールアドレスを外す": "Eliminar correo",
  "メールアドレスを外しました。": "Correo eliminado.",
  "合言葉を変える": "Cambiar contraseña",
  "新しい合言葉を入れてください。": "Introduce una nueva contraseña.",
  "合言葉を変えました。": "Contraseña cambiada.",
  "死鏡団地": "Shikyou Danchi",
  "四号棟・解体前夜": "Bloque Cuatro · La noche antes de la demolición",
  "死鏡団地 四号棟。": "Shikyou Danchi. Bloque Cuatro.",
  "私が十八まで住んでいた建物は、明日の朝、重機に囲まれる。": "Mañana por la mañana, las máquinas de demolición rodearán el edificio donde viví hasta los dieciocho años.",
  "母の部屋に、ノートを一冊置いたままだった。": "Había dejado un cuaderno en casa de mi madre.",
  "電気はもう止まっている。階段で上がるしかない。": "Ya han cortado la luz. Tendré que subir por las escaleras.",
  "——三十分で戻る。それだけのつもりだった。": "—Volveré en treinta minutos. Eso era todo lo que tenía pensado.",
  "階段室の鉄扉は、押すとまだ動いた。": "La puerta de hierro de la escalera aún se movía al empujarla.",
  "自分の家だったころ、傘立ての上に置いていた。": "Cuando vivía aquí, la guardaba encima del paragüero.",
  "使える電池の入った予備の懐中電灯だ。": "Una linterna de repuesto con una pila que funciona.",
  "解体工事のお知らせ": "Aviso de demolición",
  "死鏡団地 四号棟": "Shikyou Danchi · Bloque Cuatro",
  "八月三十一日をもって": "A partir del 31 de agosto",
  "立入を禁止いたします": "queda prohibida la entrada",
  "死鏡団地管理組合": "Asociación de residentes",
  "懐中電灯は、たしか玄関の靴箱の上だ。": "La linterna debería estar en el zapatero de la entrada.",
  "……風の音しかしない。": "…Solo se oye el viento.",
  "二階": "Planta 2",
  "郵便受けの列が、まだ名前を貼ったまま残っている。": "Los buzones siguen en fila, con todas sus placas de nombres.",
  "階段の扉に、南京錠がかかっている。": "Hay un candado en la puerta de la escalera.",
  "台所の壁のフックに、鍵が一本ぶら下がっていた。": "Una llave cuelga de un gancho en la pared de la cocina.",
  "二〇二号室。あの子の家だ。": "Piso 202. Aquí vivía aquel niño.",
  "——上で、何か落ちた。": "—Algo se ha caído arriba.",
  "扉が、ひとりでに閉まった。": "Una puerta se ha cerrado sola.",
  "三階": "Planta 3",
  "蛍光灯が一本だけ、まだ切れかけのまま生きている。": "Un único tubo fluorescente sigue parpadeando, negándose a apagarse.",
  "階段室が暗すぎて、扉の位置さえ分からない。": "La escalera está demasiado oscura. Ni siquiera distingo la puerta.",
  "廊下の端の鉄箱。中のつまみが、下がったままだ。": "La caja metálica al fondo del pasillo. El interruptor de dentro sigue bajado.",
  "管理人の詰所だった部屋。棚に日誌の切れ端が挟まっている。": "La antigua vivienda del conserje. Hay una página de diario arrancada entre los estantes.",
  "……足音が、二重に聞こえる。": "…Oigo dos pares de pasos.",
  "四階": "Planta 4",
  "四階。ここで折り返せば、あと一つ上だ。": "Cuarta planta. Tras este giro, solo queda un tramo más.",
  "……四階。いま、上ったはずだ。": "…Cuarta planta. Pero si acabo de subir.",
  "号室の札が、全部同じ数字になっている。": "Todas las puertas tienen el mismo número.",
  "四階。四階。四階。": "Cuarta planta. Cuarta planta. Cuarta planta.",
  "一つだけ、扉が開いている。": "Solo hay una puerta abierta.",
  "五階": "Planta 5",
  "五階だけ、廊下の灯りがついていた。": "Solo estaba iluminado el pasillo de la quinta planta.",
  "自分の家。表札はまだ外されていない。": "Mi casa. La placa con el nombre sigue ahí.",
  "……電気は止まっているはずだ。": "…Se supone que han cortado la luz.",
  "自分の家だったころの部屋。畳の目まで覚えている。": "La habitación que antes era mi hogar. Recuerdo hasta el tejido del tatami.",
  "靴箱を見る": "Examinar zapatero",
  "傘立ての上。やっぱり、そこにあった。": "Encima del paragüero. Justo donde recordaba.",
  "一〇二号室。佐々木さんの家だ。仏間の匂いがまだ残っている。": "Piso 102. La casa de los Sasaki. Aún perdura el olor de la habitación del altar.",
  "仏壇を見る": "Examinar altar",
  "線香が、途中まで燃えて折れている。灰はまだ温かい。": "Una varilla de incienso yace partida, consumida a medias. La ceniza aún está tibia.",
  "引っ越しの途中で止まったまま、十何年たった部屋。": "Una mudanza que quedó a medias hace más de diez años.",
  "段ボールを開ける": "Abrir caja de cartón",
  "衣類。いちばん下に、髪の毛が一束、輪ゴムでまとめてある。": "Ropa. En el fondo, un mechón de pelo atado con una goma.",
  "子ども部屋。柱に、背の高さの傷が並んでいる。": "Un cuarto infantil. Hay marcas de altura en un pilar de madera.",
  "傷を数える": "Contar las marcas",
  "十二本ある。最後の一本だけ、天井近くに刻まれている。": "Doce marcas. Solo la última está tallada cerca del techo.",
  "からっぽの部屋。家財の跡だけが、畳に焼きついている。": "Una habitación vacía. En el tatami solo quedan las sombras de los muebles.",
  "畳の跡を見る": "Examinar marcas del tatami",
  "箪笥、卓袱台、それから——人がひとり、ずっと座っていた形。": "Una cómoda, una mesa baja y… la silueta de alguien que estuvo sentado allí mucho tiempo.",
  "袋の山。中身は分からない。踏むと、やわらかい。": "Montones de bolsas. No sé qué contienen. Se hunden bajo mis pies.",
  "袋を見る": "Examinar bolsas",
  "いちばん上の袋が、いま、ゆっくり沈んだ。": "La bolsa de arriba acaba de hundirse, lentamente.",
  "水回りの部屋。奥の扉の向こうから、水の音がする。": "Un cuarto de baño. Al otro lado de la puerta del fondo corre agua.",
  "風呂の扉を開ける": "Abrir puerta del baño",
  "音が止んだ。浴槽は乾ききっている。髪だけが、排水口から伸びている。": "El sonido se detuvo. La bañera está completamente seca. Solo salen pelos del desagüe.",
  "姿見が三枚、壁に立てかけてある。どれも布がかけてあった形跡がある。": "Tres espejos de cuerpo entero apoyados en la pared. Parece que antes estaban cubiertos.",
  "鏡を覗く": "Mirarse en el espejo",
  "自分が映っている。……こちらを向くのが、一拍おそい。": "Mi reflejo. …Se vuelve hacia mí un instante demasiado tarde.",
  "二〇五号室。高木さんの家。万年床が敷きっぱなしだ。": "Piso 205. La casa de los Takagi. Han dejado un futón extendido.",
  "布団に触れる": "Tocar futón",
  "へこんでいる。人の形に。まだ、温かい。": "Una hendidura. Con forma humana. Aún está caliente.",
  "三〇一号室。中村さんの家。花瓶がいくつも並んでいる。": "Piso 301. La casa de los Nakamura. Hay floreros puestos en fila.",
  "花瓶を見る": "Examinar floreros",
  "花はすべて枯れている。水だけが、新しい。": "Todas las flores están muertas. Solo el agua está fresca.",
  "物置。家財が天井まで積み上がって、奥へは行けない。": "Un almacén. Los muebles llegan hasta el techo y bloquean el paso.",
  "すきまを覗く": "Mirar por el hueco",
  "奥に、たんすが一棹。その陰から、こちらを見ている。": "Una cómoda al fondo. Algo mira desde detrás de ella.",
  "書類棚を見る": "Examinar archivador",
  "住民名簿。八月のところで、名前が一つずつ、線で消されている。": "El registro de residentes. En agosto, los nombres se han ido tachando uno a uno.",
  "テレビがついている。電気は止まっているはずだ。": "El televisor está encendido. Se supone que no hay electricidad.",
  "画面を見る": "Mirar la pantalla",
  "砂嵐——のあいだに、いま歩いてきた廊下が、一瞬だけ映った。": "Entre las interferencias apareció por un instante el pasillo por el que acabo de pasar.",
  "子ども部屋。ぬいぐるみが棚に並んでいる。全部、壁を向いている。": "Un cuarto infantil. Hay peluches en los estantes. Todos miran hacia la pared.",
  "ぬいぐるみを見る": "Examinar peluches",
  "顔をこちらに直した。……一つだけ、もともとこちらを向いていた。": "Les di la vuelta para que me miraran. …Uno ya me estaba mirando.",
  "何もない。畳だけが、新しく替えられている。": "No hay nada. Solo han cambiado el tatami.",
  "畳を見る": "Examinar tatami",
  "四階の畳だけ、どこも新しい。替える必要が、あったのだろうか。": "Todo el tatami de la cuarta planta es nuevo. ¿Por qué hubo que cambiarlo?",
  "段ボールに、几帳面な字で中身が書いてある。": "El contenido de cada caja está escrito con letra cuidada.",
  "字を読む": "Leer etiquetas",
  "「たいせつなもの」。全部の箱に、同じ字で。": "«Cosas valiosas». Todas las cajas, con la misma letra.",
  "壁という壁に、鏡が貼りつけてある。合わせ鏡になっている。": "Los espejos cubren todas las paredes, unos frente a otros.",
  "合わせ鏡を覗く": "Mirar entre los espejos",
  "奥へ、奥へ、自分が続いている。……七番目から、数が合わない。": "Mis reflejos se prolongan sin fin. …A partir del séptimo, la cuenta no encaja.",
  "四〇四号室。表札の枠だけが残っている。": "Piso 404. De la placa con el nombre solo queda el marco.",
  "部屋を見まわす": "Mirar la habitación",
  "誰も住んでいない部屋のはずが、掃除が行き届いている。": "Esta habitación debería estar vacía, pero alguien la mantiene impecable.",
  "布団が敷いてある。まんなかが、ふくらんでいる。": "Hay un futón extendido. Algo abulta bajo el centro.",
  "布団をめくる": "Levantar el edredón",
  "何もない。掛け布団の内側だけが、人肌の温度をしている。": "Nada. Solo la cara interior del edredón está tan caliente como un cuerpo.",
  "花の匂いがする。枯れているのに。": "Las flores huelen dulcemente. Aunque están muertas.",
  "花を見る": "Examinar flores",
  "供花だ。名札に、この棟の号室が書いてある。全部で四つ。": "Flores funerarias. Las tarjetas indican pisos de este edificio. Cuatro en total.",
  "がらんとした部屋。窓だけが、きれいに拭いてある。": "Una habitación vacía. Solo han limpiado la ventana.",
  "窓を見る": "Examinar ventana",
  "内側から拭いてある。指の跡が、外側にも同じだけ付いている。": "La limpiaron por dentro. Fuera hay el mismo número de huellas dactilares.",
  "姿見が一枚。ちょうど、玄関を映す向きに置いてある。": "Un espejo de cuerpo entero colocado para reflejar la entrada.",
  "鏡を見る": "Examinar espejo",
  "玄関が映っている。いま閉めたはずの扉が、開いている。": "Se ve la entrada reflejada. La puerta que acabo de cerrar está abierta.",
  "母が出ていった日のまま。灰皿の上で、線香が一本、燃え尽きている。": "Todo sigue como cuando mamá se fue. Una sola varilla de incienso se ha consumido sobre el cenicero.",
  "仏間。位牌がいくつも並んでいる。数が多すぎる。": "Una habitación con un altar. Filas de tablillas conmemorativas. Demasiadas.",
  "位牌を数える": "Contar tablillas conmemorativas",
  "十九。この棟に住んでいた世帯の数と、同じだ。": "Diecinueve. Tantas como familias vivían aquí.",
  "回覧板の切れ端": "Aviso circular rasgado",
  "一階・掲示板": "Planta 1 · Tablón de anuncios",
  "＜解体工事に伴う立入禁止のお知らせ＞": "PROHIBIDO EL PASO — DEMOLICIÓN",
  "八月三十一日をもって、四号棟への立入を": "A partir del 31 de agosto, la entrada al Bloque Cuatro",
  "全面的に禁止いたします。": "queda terminantemente prohibida.",
  "室内に残された私物につきましては、": "La asociación no se responsabiliza",
  "当組合では一切の責任を負いかねます。": "de los objetos personales que permanezcan en el edificio.",
  "なお、四号棟にお住まいの方は": "Se informa de que el número de familias",
  "現在ゼロ世帯となっております。": "que residen actualmente en el Bloque Cuatro es cero.",
  "……この「ゼロ世帯」の上に、": "…Alguien ha trazado una línea a lápiz",
  "誰かが鉛筆で線を引いて、": "sobre las palabras «cero familias»",
  "「うそ」と書いてある。": "y ha escrito «mentira» encima.",
  "宛名のない葉書": "Postal sin destinatario",
  "二階・郵便受け": "Planta 2 · Buzones",
  "消印は十二年前。切手は貼られていない。": "El matasellos es de hace doce años. No tiene sello.",
  "宛名の欄は、まっさらのままだ。": "El espacio de la dirección está completamente vacío.",
  "　まだ いるのですか": "    sigues ahí",
  "　こちらは かわりません": "    aquí nada ha cambiado",
  "　あかりは つけたままにしてあります": "    hemos dejado las luces encendidas",
  "　かえってくるなら 五かいまで": "    si vuelves ve a la quinta planta",
  "裏を返すと、鉛筆で薄く": "Detrás, escrito débilmente a lápiz,",
  "「504」とだけ書いてある。": "solo aparece el número «504».",
  "台所のメモ": "Nota de la cocina",
  "二〇二号室": "Piso 202",
  "冷蔵庫に、マグネットで留まっていた。": "Estaba sujeta al frigorífico con un imán.",
  "　・かいだんの かぎ フックにかけた": "    • llave de la escalera en el gancho",
  "　・よるは でないこと": "    • no salgas de noche",
  "　・おとを たてないこと": "    • no hagas ruido",
  "三つ目だけ、何度もなぞって書いてある。": "Solo la tercera línea está repasada una y otra vez.",
  "管理日誌（切れ端）": "Diario del conserje (fragmento)",
  "三〇三号室": "Piso 303",
  "八月十四日　晴": "14 de agosto — Despejado",
  "　四号棟、巡回。異常なし。": "    Bloque Cuatro. Ronda habitual. Sin novedades.",
  "八月十七日　曇": "17 de agosto — Nublado",
  "　深夜二時、四階で足音の苦情。": "    Dos de la mañana. Queja por pasos en la cuarta planta.",
  "　行ってみたが誰もいない。": "    Fui a comprobarlo. No había nadie.",
  "　四階は先月から全戸空き家のはず。": "    Todos los pisos de la cuarta planta deberían estar vacíos desde el mes pasado.",
  "八月二十日": "20 de agosto",
  "　五〇四号室の灯りがついている。": "    Hay luz en el piso 504.",
  "　電気は先々月に止めたはずだ。": "    Se suponía que habían cortado la electricidad hace dos meses.",
  "　管理会社に確認するよう申し送る。": "    Pedir a la administración que lo revise.",
  "八月二十二日": "22 de agosto",
  "　四階から下りられない。": "    No puedo bajar de la cuarta planta.",
  "　同じ階に出る。四回": "    Siempre acabo en la misma planta. Cuatro veces",
  "（ここで文字が途切れている）": "(La escritura termina aquí.)",
  "壁の落書き": "Pintadas en la pared",
  "四階・廊下": "Planta 4 · Pasillo",
  "低い位置に、子どもの背丈で書いてある。": "Escrito en la parte baja de la pared, a la altura de un niño.",
  "クレヨンが、コンクリートに食い込んでいる。": "La cera ha dejado surcos profundos en el hormigón.",
  "　４かいは かえれない": "    de la planta 4 no se vuelve",
  "同じ行が、壁の端まで続いている。": "La misma frase se repite hasta el final de la pared.",
  "最後の一行だけ、字が大人のものだ。": "Solo la última línea tiene letra de adulto.",
  "　むかえに いきます": "    vendré a buscarte",
  "母の手紙": "Carta de mamá",
  "四〇四号室": "Piso 404",
  "封も切られていない。宛名は私の名前だ。": "El sobre está sin abrir. Va dirigido a mí.",
  "消印は、母が入院した日の少し前だった。": "El matasellos es de poco antes de que mamá ingresara en el hospital.",
  "　あなたが小さかったころ、毎朝この廊下を手をつないで歩きました。": "    Cuando eras pequeño, recorríamos este pasillo de la mano cada mañana.",
  "　雨の日に窓から電車を数えたことも、五〇四号室で背を測ったことも、": "    Contábamos trenes por la ventana los días de lluvia, medíamos tu altura en el piso 504…",
  "　私には、ここで過ごした時間がいちばん大切な宝物です。": "    El tiempo que pasamos aquí es mi tesoro más preciado.",
  "　あなたが団地を離れて、自分の暮らしを始めたことをうれしく思っています。": "    Me alegra que dejaras la urbanización y empezaras tu propia vida.",
  "　会いに来られないことを責めないで。病気のことを伝えなかったのは私です。": "    No te culpes por no visitarme. Fui yo quien te ocultó mi enfermedad.",
  "　元気なあなたの邪魔をしたくありませんでした。": "    No quería ser un obstáculo en tu vida.",
  "　解体の話を聞いて、せめて思い出の場所だけは守りたいと思いました。": "    Cuando supe lo de la demolición, quise proteger al menos el lugar de nuestros recuerdos.",
  "　住民の名前と、この建物であったことをノートに残しています。": "    Estoy anotando en un cuaderno los nombres de los vecinos y lo que ocurrió aquí.",
  "　建物はなくなっても、あなたが覚えていれば、あの日々はなくなりません。": "    Aunque el edificio desaparezca, aquellos días seguirán vivos mientras los recuerdes.",
  "　鏡に私のようなものが映っても、私だと思って残らないでください。": "    Si aparece algo parecido a mí en un espejo, no te quedes pensando que soy yo.",
  "　あれは、会えなかったあなたの後悔と、この団地の記憶が作った影です。": "    Es una sombra hecha de tu pesar por no haberme visto y de los recuerdos de este lugar.",
  "　私はあなたを閉じ込めたいのではありません。": "    Yo no quiero retenerte aquí.",
  "　最後に、会って言いたかったことは一つだけです。": "    Solo había una cosa que quería decirte en persona, una última vez.",
  "　元気でね。あなたのこれからを、ずっと願っています。": "    Cuídate. Siempre desearé que tengas una buena vida.",
  "　　　　　　　　　　　　　　母": "                            Mamá",
  "母のノート": "Cuaderno de mamá",
  "五〇四号室": "Piso 504",
  "表紙に、四号棟の見取り図が描いてある。": "En la cubierta hay un plano del Bloque Cuatro.",
  "住戸の一つ一つに、名前と、退去した日。": "Cada vivienda tiene un nombre y una fecha de mudanza.",
  "余白には、その家の匂いや、よく聞こえた笑い声まで書かれている。": "En los márgenes están los olores de esas casas, incluso las risas que solía oír.",
  "　一〇二　佐々木さん　　三月　　朝に味噌汁の匂い": "    102  Los Sasaki — Marzo — Sopa de miso por las mañanas",
  "　二〇五　高木さん　　　五月　　雨の日に歌う子": "    205  Los Takagi — Mayo — Un niño cantando los días de lluvia",
  "　三〇一　中村さん　　　七月　　鉢植えを分けてくれた": "    301  Los Nakamura — Julio — Compartieron sus plantas en maceta",
  "　五〇四　私たち　　　　十八年　息子と暮らした家": "    504  Nosotros — Dieciocho años — La casa que compartí con mi hijo",
  "ページをめくるたび、幼い私の絵や身長の印、母の短い日記が挟まっている。": "Entre las páginas hay dibujos de mi infancia, marcas de altura y breves anotaciones del diario de mamá.",
  "母は病室へ移ってからも、管理組合へ何通も手紙を書いていた。": "Incluso después de ingresar en el hospital, mamá siguió escribiendo a la asociación de residentes.",
  "この団地を残してほしい、と。ここは息子と生きた証だから、と。": "Por favor, salven esta urbanización, escribía. Es la prueba de la vida que compartí con mi hijo.",
  "最後のページだけ、文章が途中で途切れている。": "Solo la última página termina con una frase incompleta.",
  "　もう一度会えたら、謝らせず、引き止めず、笑って――": "    Si pudiera verlo una vez más, no le dejaría disculparse ni le pediría que se quedara. Sonreiría y…",
  "その下に、看護師らしい別の筆跡で一行が添えられている。": "Debajo hay una frase con otra letra, quizá la de una enfermera.",
  "　最期まで、息子さんに『元気でね』と伝えたいと話していました。": "    Hasta el último momento dijo que quería decirle a su hijo: «Cuídate».",
  "懐中電灯。電池はもう長くない。": "Una linterna. La pila no durará mucho más.",
  "予備の懐中電灯": "Linterna de repuesto",
  "電池の入った懐中電灯に持ち替えた。": "Has cambiado a una linterna con una pila que funciona.",
  "予備の電池": "Pila de repuesto",
  "電池を一本、見つけた。": "Has encontrado una pila.",
  "階段の鍵": "Llave de la escalera",
  "階段の鍵。南京錠のものだ。": "La llave del candado de la escalera.",
  "……おかえり": "…bienvenido a casa",
  "……まだ いる": "…sigues aquí",
  "……ごう しつ": "…número de piso",
  "……あかり つけて": "…enciende la luz",
  "……よん かい": "…cuarta planta",
  "……ふりむかないで": "…no te des la vuelta",
  "……わすれないで": "…no lo olvides",
  "見られている。": "Algo está mirando.",
  "走るな。音を立てるな。": "No corras. No hagas ruido.",
  "扉の中へ。": "Por la puerta.",
  "近い。": "Cerca.",
  "肩に、手が触れた。": "Una mano me tocó el hombro.",
  "冷たくはなかった。子どものころ、母とつないだ手の温度だった。": "No estaba fría. Tenía el calor de la mano de mamá cuando yo era niño.",
  "会えないまま母を亡くした私は、その手を離せなかった。": "La había perdido sin volver a verla. No podía soltar aquella mano.",
  "鏡の影は母の顔で、『行かないで』と私の後悔を繰り返す。": "La sombra del espejo tenía el rostro de mamá. «No te vayas», decía, repitiendo mi propio pesar.",
  "けれど、それは母が言いたかった言葉ではない。": "Pero esas no eran las palabras que ella había querido decir.",
  "郵便受けに私の名前の札が戻り、四〇四号室の扉が閉じた。": "Mi nombre volvió a un buzón y la puerta del piso 404 se cerró.",
  "母が外で生きることを願ったと知らないまま、私は思い出の中に残った。": "Sin saber que mamá quería que viviera fuera, me quedé atrapado en los recuerdos.",
  "外": "Fuera",
  "団地の玄関を抜けると、夜明け前の風が頬に触れた。": "Al salir del edificio, el viento previo al amanecer me rozó la mejilla.",
  "背後で、濡れた裸足の音が敷居の内側で止まった。": "A mi espalda, los pasos de unos pies descalzos y mojados se detuvieron justo dentro del umbral.",
  "振り返ると、四号棟はただの古い建物だった。": "Al mirar atrás, el Bloque Cuatro no era más que un edificio viejo.",
  "母が守ろうとした場所を、私はまだ思い出しきれない。": "Aún no conseguía recordar del todo el lugar que mamá había intentado proteger.",
  "それでも鞄のノートを抱き、前を向いて歩いた。": "Aun así, abracé el cuaderno que llevaba en el bolso y seguí caminando.",
  "五〇四号室の灯りが二度またたく。": "La luz del piso 504 parpadeó dos veces.",
  "風にまぎれて、聞き取れないほど小さな母の声がした。": "La voz de mamá, perdida entre el viento, apenas se oía.",
  "——三か月後、建物はなくなった。": "—Tres meses después, el edificio ya no estaba.",
  "更地の前で、私はようやく母の名前を声に出した。": "Ante el solar vacío, por fin pronuncié el nombre de mamá en voz alta.",
  "おぼえている": "Lo recuerdo",
  "団地の玄関を抜ける。空は、夜と朝のあいだの色をしていた。": "Salí del edificio. El cielo estaba entre la noche y la mañana.",
  "外へ出た瞬間、追ってきた足音が敷居の内側で止まった。": "En cuanto salí, los pasos que me perseguían se detuvieron justo dentro del umbral.",
  "ガラス戸に『それ』が映る。母の顔で、私を団地へ引き戻そうとしていた。": "La Presencia apareció en el cristal de la puerta. Con el rostro de mamá, intentó atraerme de nuevo al interior.",
  "でも、あれは母ではない。会えなかった後悔と、失われる場所への恐れだ。": "Pero no era mamá. Era mi pesar por no haberla visto y mi miedo a perder este lugar.",
  "母は、この団地に私を閉じ込めようとしたのではなかった。": "Mamá nunca había querido encerrarme en esta urbanización.",
  "私と過ごした日々が消えないように、たった一人で守ろうとしていたのだ。": "Había intentado, ella sola, evitar que desaparecieran los días que compartimos.",
  "幼い私と母が手をつないで階段を降りる記憶が、朝の窓に重なった。": "En la ventana iluminada por la mañana vi el recuerdo de los dos bajando la escalera de la mano.",
  "『いってらっしゃい』": "«Que tengas un buen día».",
  "その声に、私は初めて前を向いたまま答えた。": "Por primera vez, respondí sin mirar atrás.",
  "『行ってきます』": "«Me voy, entonces».",
  "五〇四号室の灯りが、二度またたいて消えた。": "La luz del piso 504 parpadeó dos veces y se apagó.",
  "『それ』の顔から母の面影がほどけ、暗い玄関の奥へ消えていった。": "Los rasgos de mamá se deshicieron en el rostro de la Presencia, que desapareció en la entrada oscura.",
  "——建物は、夏の終わりになくなった。": "—El edificio fue demolido al terminar el verano.",
  "私はノートを開き、団地で母と笑った日のことを書き続けている。": "Aún abro el cuaderno y escribo sobre los días en que mamá y yo reíamos juntos aquí.",
  "場所はなくなっても、母が守りたかった時間は、私の中に残っている。": "El lugar ya no existe, pero el tiempo que ella quiso proteger vive dentro de mí.",
  "最後のページに、病室の母が託した本当の言葉がある。": "En la última página están las palabras que mamá realmente me dejó desde la cama del hospital.",
  "『元気でね』": "«Cuídate».",
  "私は泣きながら笑って、朝の道を歩き出した。": "Entre lágrimas y sonrisas, eché a andar por el camino al amanecer.",
  "階段室の外扉を調べ、団地の外へ出ます。": "Examina la puerta exterior de la escalera y sal de la urbanización.",
  "懐中電灯を拾う": "Encuentra la linterna",
  "一〇一号室の扉を開けて、中に入ります。": "Abre la puerta del piso 101 y entra.",
  "玄関を入ってすぐ右、靴箱の上に置いてあります。": "Está sobre el zapatero, justo a la derecha al entrar.",
  "拾ったら、階段室へ戻って「上る」。": "Cuando la tengas, vuelve a la escalera y elige «Subir».",
  "二階へ上がる": "Ve a la segunda planta",
  "廊下の左端が階段室です。中で「上る」を選びます。": "La escalera está en el extremo izquierdo del pasillo. Entra y elige «Subir».",
  "階段の鍵を探す": "Encuentra la llave de la escalera",
  "階段の扉に南京錠がかかっています。": "La puerta de la escalera tiene un candado.",
  "鍵は 二〇二号室 の台所、壁のフックにぶら下がっています。": "La llave cuelga de un gancho en la cocina del piso 202.",
  "二〇二号室は、階段室から二番目の扉です。": "El piso 202 es la segunda puerta desde la escalera.",
  "三階へ上がる": "Ve a la tercera planta",
  "鍵は持っています。階段室へ戻って「上る」。": "Ya tienes la llave. Vuelve a la escalera y elige «Subir».",
  "分電盤のつまみを上げる": "Sube el interruptor del cuadro eléctrico",
  "階段室が暗すぎて、扉の位置が分かりません。": "La escalera está demasiado oscura para ver la puerta.",
  "廊下を いちばん奥（階段室と反対の端）まで歩くと、": "Ve al extremo del pasillo opuesto a la escalera.",
  "壁に灰色の鉄の箱が付いています。それが分電盤です。": "La caja metálica gris de la pared es el cuadro eléctrico.",
  "近づいて「開ける」を選ぶと、明かりがつきます。": "Acércate y elige «Abrir» para encender las luces.",
  "※この階には「それ」がいます。出会ったら、": "La Presencia está en esta planta. Si te encuentras con ella,",
  "　まんなかを避けて、どちらかの壁ぎわに寄ってください。": "    evita el centro y acércate a una de las paredes laterales.",
  "　寄ればすれ違えます。正面から向かうとつかまります。": "    Puedes pasar por los bordes. Si vas de frente, te atrapará.",
  "　開いている扉に飛び込んでも助かります。": "    También puedes refugiarte en un piso abierto.",
  "四階へ上がる": "Ve a la cuarta planta",
  "明かりはつきました。階段室へ戻って「上る」。": "Las luces están encendidas. Vuelve a la escalera y elige «Subir».",
  "つまみを上げた音で「それ」が寄ってきています。": "El sonido del interruptor ha atraído a la Presencia.",
  "危なくなったら、開いている住戸へ飛び込んでください。": "Si estás en peligro, corre hacia un piso abierto.",
  "四階から抜け出す": "Escapa de la cuarta planta",
  "上っても、また四階に出ます。それでかまいません。": "Al subir vuelves a la cuarta planta. Es parte del juego.",
  "二度、上ってください。三度目の四階は廊下が短く、": "Sube dos veces. La tercera versión de la cuarta planta tiene un pasillo más corto",
  "扉がひとつだけ開いています。": "y una sola puerta abierta.",
  "その部屋の文机にある「母の手紙」を読むと、抜けられます。": "Lee la carta de mamá sobre el escritorio de ese piso para salir del bucle.",
  "五階へ上がる": "Ve a la quinta planta",
  "手紙は読みました。階段室から「上る」。": "Has leído la carta. Elige «Subir» en la escalera.",
  "母のノートを取る": "Recoge el cuaderno de mamá",
  "五〇四号室に入ります。階段室から四番目の扉です。": "Entra en el piso 504, la cuarta puerta desde la escalera.",
  "いちばん奥の部屋、机の上にノートがあります。": "El cuaderno está sobre la mesa del cuarto del fondo.",
  "取ったら、廊下の照明が全部落ちます。走って階段室へ。": "Al recogerlo se apagan todas las luces del pasillo. Corre a la escalera.",
  "階段室で「下りる」を選び、一階まで降りて外へ。": "Elige «Bajar» en la escalera. Sigue hasta la primera planta y sal del edificio.",
  "階段室へ": "Ve a la escalera",
  "廊下の左端が階段室です。": "La escalera está en el extremo izquierdo del pasillo.",
  "正面から向かっていくと、必ずつかまる": "Si vas de frente, te atrapará",
  "廊下の幅は2.55m。まんなかを進むとぶつかります。扉側か手すり側の、どちらかの壁ぎわに寄ってください。寄れば、すれ違って逃げられます。": "El pasillo mide 2,55 metros de ancho. Acércate a las puertas o a la barandilla en vez de ir por el centro. Puedes pasar por cualquiera de los bordes.",
  "住戸の中と階段室には入ってこない": "Los pisos y las escaleras ofrecen refugio",
  "「それ」が出る階では、はじめから開いている扉がいくつかあります。飛び込めば助かります。中にいるあいだは追ってきません。": "En las plantas donde aparece la Presencia, algunas puertas empiezan abiertas. Refúgiate dentro: no entrará en los pisos. Durante la huida final sí te seguirá escaleras abajo.",
  "走ると、足音でまず見つかる": "Correr revela tu posición",
  "走る＞歩く＞しゃがむ の順に響きます。近くにいるときは、しゃがんで動いてください。": "Correr hace más ruido, seguido de caminar y moverse en cuclillas. Agáchate cuando esté cerca.",
  "懐中電灯は、見つかる元でもある": "La linterna puede delatarte",
  "遠くからでも光が見えます。危ないと思ったら消してください（灯／F キー）。": "Su haz se ve desde lejos. Apágala si sientes peligro (Luz / F).",
  "正面から光を当てると、一瞬止まる": "Alumbrarla de frente la detiene un instante",
  "そのすきに逃げられます。ただし何度も効きません。止まったあとは速くなります。": "Aprovecha para escapar. No funciona repetidamente y después se mueve más rápido.",
  "心臓の音が速くなったら、近い": "La pantalla avisa del peligro cercano",
  "画面のふちが暗く赤くなり、すぐ後ろにいると息づかいが聞こえます。": "Los bordes se oscurecen y se tiñen de rojo cuando se acerca el peligro.",
  "つかまっても、その階の最初からやり直せる": "Si te atrapa, reintenta desde el inicio de esa planta",
  "進み具合（メモや持ち物）は消えません。": "Conservas las notas y los objetos recogidos.",
  "ひとりでに起きることは、こわいだけで害はない": "Los fenómenos extraños asustan, pero no te hacen daño",
  "鍋が落ちる、扉が揺れる、勝手に開く、灯りが消えてまた点く、壁に血が滲む、無かったはずの靴が落ちている——どれも触ってきません。「それ」とは別のものです。おどろいて走ると、かえって足音で見つかります。": "Ollas que caen, puertas que tiemblan, luces que se apagan, sangre en las paredes, zapatos que antes no estaban… Nada de eso puede tocarte. Son fenómenos distintos de la Presencia. Correr por el pánico puede delatarte.",
  "移動": "Moverse",
  "マウス": "Ratón",
  "見まわす": "Mirar alrededor",
  "走る（音が響く）": "Correr (ruidoso)",
  "しゃがむ（静かに歩く）": "Agacharse (silencioso)",
  "E / クリック": "E / Clic",
  "調べる・開ける": "Examinar / Abrir",
  "ポーズ": "Pausa",
  "左スティック": "Palanca izquierda",
  "画面を なぞる": "Arrastrar la pantalla",
  "調": "Usar",
  "走": "Correr",
  "走る": "Correr",
  "屈": "Agachar",
  "しゃがむ": "Agachar",
  "灯": "Luz",
  "帳": "Notas",
  "持ち物": "Inventario",
  "<p class=\"dim\">なにも持っていない。</p>": "<p class=\"dim\">No llevas nada.</p>",
  "・": "•",
  "見つけたもの　": "Hallazgos: ",
  "操作": "Controles",
  "<div>見つけたもの　": "<div>Hallazgos: ",
  "<div>かかった時間　": "<div>Tiempo: ",
  "もう一度": "Jugar de nuevo",
  "はじめての方へ · {0}/2": "Guía rápida · {0}/2",
  "<ol><li>Safariでこのゲームを開きます。</li><li><span class=\"welcome-phrase\">共有ボタンを押します。</span><br><span class=\"welcome-phrase\">四角から上向き矢印の</span><span class=\"welcome-phrase\">マークです。</span><br><span class=\"welcome-phrase\">見当たらないときは</span><span class=\"welcome-phrase\">メニュー内を確認します。</span></li><li><span class=\"welcome-phrase\">「ホーム画面に追加」</span>を選び、<span class=\"welcome-phrase\">「追加」を押します。</span><br><span class=\"welcome-phrase\">「Webアプリとして開く」</span><span class=\"welcome-phrase\">が表示されたら</span><span class=\"welcome-phrase\">オンにします。</span></li></ol>": "<ol><li>Abre el juego en Safari.</li><li>Toca Compartir (el cuadrado con una flecha hacia arriba). Si no aparece, busca en el menú del navegador.</li><li>Elige «Añadir a pantalla de inicio» y después «Añadir». Si aparece «Abrir como app web», actívalo.</li></ol>",
  "<ol><li>Chromeでこのゲームを開きます。</li><li>右上の「⋮」メニューを開きます。</li><li><span class=\"welcome-phrase\">「ホーム画面に追加」</span>を選びます。表示が異なる場合は「インストールしてショートカットを作成」を選び、案内に沿って追加します。</li></ol>": "<ol><li>Abre el juego en Chrome.</li><li>Abre el menú ⋮ de arriba a la derecha.</li><li>Elige «Añadir a pantalla de inicio» o la opción de instalar o crear un acceso directo, y sigue las indicaciones.</li></ol>",
  "<ol><li>ChromeまたはEdgeでこのゲームを開きます。</li><li>ブラウザーのメニューから、アプリのインストールやショートカットの作成を選びます。</li><li>画面の案内に沿って追加します。</li></ol>": "<ol><li>Abre el juego en Chrome o Edge.</li><li>En el menú del navegador, elige instalar la aplicación o crear un acceso directo.</li><li>Sigue las indicaciones para terminar.</li></ol>",
  "<strong>ホーム画面から起動できています</strong><p>追加の操作は必要ありません。そのまま遊べます。</p>": "<strong>Ya has abierto el juego desde la pantalla de inicio</strong><p>Todo listo. No hace falta hacer nada más.</p>",
  "追加されました。次からはホーム画面のアイコンから開けます。": "Añadido. La próxima vez, abre el juego desde su icono en la pantalla de inicio.",
  "追加手続きを受け付けました。端末の案内をご確認ください。": "Se ha solicitado la instalación. Sigue las indicaciones del dispositivo.",
  "追加はあとからでもできます。上の手順からお試しください。": "Puedes añadirlo más tarde siguiendo los pasos anteriores.",
  "上のブラウザーのメニュー操作で追加できます。": "Usa el menú del navegador y los pasos anteriores para añadir el juego.",
  "電池": "Pila",
  "休": "Pausa",
  "閉じる": "Cerrar",
  "手帳": "Cuaderno",
  "小休止": "Pausa",
  "記録が二つあります": "Dos partidas guardadas",
  "この端末とクラウドで、進み具合が違います。どちらで続けますか。": "Tu partida local y la de la nube son distintas. ¿Cuál quieres continuar?",
  "この端末": "Este dispositivo",
  "この端末の記録で続ける": "Continuar partida local",
  "クラウド": "Nube",
  "クラウドの記録で続ける": "Continuar partida en la nube",
  "鬼ごっこ": "Persecución multijugador",
  "2〜4人。ひとりが「それ」になり、残りは鍵を三本あつめて階段室から逃げます。": "De 2 a 4 jugadores. Uno será la Presencia. Los demás deben reunir tres llaves y escapar por la escalera.",
  "どの階で遊ぶか": "Elige una planta",
  "部屋をつくる": "Crear sala",
  "友達の合言葉を入れる": "Introduce el código de tu amigo",
  "その部屋に入る": "Unirse a la sala",
  "この合言葉を、友達に伝えてください。": "Comparte este código con tus amigos.",
  "友達がつながると、ここに名前が出ます。": "Los nombres de tus amigos aparecerán aquí cuando se conecten.",
  "部屋を作った人が審判をします。その人の画面を裏にすると、みんなの進行が止まります。": "El anfitrión dirige la partida. Si sale del juego, se pausa para todos.",
  "ログインしておくと、パソコンでもスマホでも、同じところから続きを遊べます。": "Inicia sesión para continuar tu partida en un ordenador o teléfono.",
  "メールアドレスは入れても入れなくてもかまいません。": "El correo electrónico es opcional.",
  "「": "Continuar como ",
  "」で続ける": "",
  "はじめて": "Registrarse",
  "この端末だけ": "Invitado",
  "名前　または　メールアドレス": "Nombre o correo electrónico",
  "かえで　または　you@example.com": "Tu nombre o tu@ejemplo.com",
  "名前（ログインに使います）": "Nombre (para iniciar sesión)",
  "2〜16文字・空白なし": "De 2 a 16 caracteres, sin espacios",
  "ローマ字でも、ひらがなでもかまいません。": "Puedes usar caracteres latinos o japoneses.",
  "合言葉": "Contraseña",
  "4文字以上": "Al menos 4 caracteres",
  "メールアドレス（任意）": "Correo electrónico (opcional)",
  "空のままでも登録できます": "Puedes dejarlo vacío",
  "入れておくと、名前を忘れてもメールでログインできます。あとから登録・削除もできます。": "El correo te permite iniciar sesión si olvidas tu nombre. Puedes añadirlo o eliminarlo después.",
  "この端末の中だけに記録を残します。ほかの機械には引き継げません。": "El progreso se guarda solo en este dispositivo y no estará disponible en otros.",
  "あとからログインすれば、そのときの進み具合をそのまま預けられます。": "Inicia sesión más tarde para subir tu progreso local a la nube.",
  "ログインしないで遊ぶ": "Jugar sin iniciar sesión",
  "ヘッドホンと、暗い部屋をおすすめします。": "Se recomienda usar auriculares y jugar en una habitación oscura.",
  "スマートフォンは、横向きにすると見やすくなります。": "En el móvil, la orientación horizontal ofrece un campo de visión mayor.",
  "名前は2〜16文字。空白と @ は使えません。": "El nombre debe tener de 2 a 16 caracteres, sin espacios ni @.",
  "その名前は使われています。": "Ese nombre ya está en uso.",
  "この名前は使えます。": "Ese nombre está disponible.",
  "メールアドレスの形式が違います。": "Introduce un correo electrónico válido.",
  "その名前はすでに使われています。": "Ese nombre ya está en uso.",
  "そのメールアドレスはすでに使われています。": "Ese correo ya está registrado.",
  "名前（またはメール）と合言葉を入力してください。": "Introduce tu nombre (o correo) y contraseña.",
  "名前か合言葉が違います。": "Nombre o contraseña incorrectos.",
  "不明な操作です。": "Acción desconocida.",
  "サーバーに接続できませんでした。": "No se pudo conectar con el servidor.",
  "ログインし直してください。": "Vuelve a iniciar sesión.",
  "アカウントが見つかりませんでした。": "No se ha encontrado la cuenta.",
  "今の合言葉が違います。": "La contraseña actual es incorrecta.",
  "名前を入力してください。": "Introduce un nombre.",
  "記録の中身がありません。": "No se han proporcionado datos de la partida.",
  "記録が大きすぎます。": "Los datos de la partida son demasiado grandes.",
  "別の端末に新しい記録があります。": "Hay una partida más reciente en otro dispositivo.",
  "サーバーの準備がまだです。『この端末だけ』で遊べます。": "El servidor aún no está listo. Puedes jugar como invitado en este dispositivo.",
  "いま混み合っています。少し待ってください。": "El servidor está ocupado. Inténtalo de nuevo en unos instantes.",
  "その部屋は見つかりません。": "No se ha encontrado la sala.",
  "その部屋は時間切れです。作り直してください。": "La sala ha caducado. Crea una nueva.",
  "その部屋は、もう始まっています。": "La partida de esa sala ya ha comenzado.",
  "部屋がいっぱいです。": "La sala está llena.",
  "通信に失敗しました。": "Error de conexión.",
  "はじめての方へ · 1/2": "Guía rápida · 1/2",
  "はじめての方へ · 2/2": "Guía rápida · 2/2",
  "スキップ": "Omitir",
  "案内を閉じる": "Cerrar guía",
  "続きを守る、": "Conserva tu progreso.",
  "かんたんログイン": "Inicia sesión fácilmente.",
  "はじめる前に、": "Antes de empezar, ",
  "名前と合言葉を": "elige un nombre y una contraseña ",
  "登録しませんか？": "para crear una cuenta.",
  "メールアドレスは不要です": "No necesitas correo electrónico",
  "好きな名前と、": "Solo necesitas un nombre ",
  "4文字以上の合言葉だけで": "y una contraseña de al menos 4 caracteres ",
  "登録できます。": "para registrarte.",
  "進み具合を": "Tu progreso ",
  "クラウドに保存できます。": "puede guardarse en la nube.",
  "端末のデータが消えても、": "Aunque se pierdan los datos del dispositivo, ",
  "同じ名前と合言葉で": "usa el mismo nombre y contraseña ",
  "保存した続きから遊べます。": "para continuar tu partida en la nube.",
  "保存には通信が必要です。": "Para guardar necesitas conexión a internet. ",
  "名前と合言葉は": "Conserva tu nombre y contraseña ",
  "控えておいてください。": "en un lugar seguro.",
  "次へ：ホーム画面に追加": "Siguiente: añadir a inicio",
  "次からは、": "Un toque",
  "ホーム画面から": "para volver.",
  "ホーム画面に追加すると、": "Añade el juego a tu pantalla de inicio ",
  "アイコンを押すだけで": "para abrirlo directamente ",
  "すぐに遊べます。": "desde su icono.",
  "お使いの端末": "Tu dispositivo",
  "ホーム画面に追加する": "Añadir a pantalla de inicio",
  "追加はあとからでもできます。": "Puedes añadirlo más tarde. ",
  "ログインしてください。": "para iniciar sesión.",
  "名前と合言葉を登録する": "Crear tu cuenta",
  "Safariでこのゲームを開きます。": "Abre este juego en Safari.",
  "共有ボタンを押します。": "Toca el botón Compartir.",
  "四角から上向き矢印の": "Busca un cuadrado ",
  "マークです。": "con una flecha hacia arriba.",
  "見当たらないときは": "Si no aparece, ",
  "メニュー内を確認します。": "busca en el menú del navegador.",
  "「ホーム画面に追加」": "«Añadir a pantalla de inicio»",
  "を選び、": " y luego selecciona ",
  "「追加」を押します。": "«Añadir».",
  "「Webアプリとして開く」": "«Abrir como app web»",
  "が表示されたら": ": si aparece esta opción, ",
  "オンにします。": "actívala.",
  "Chromeでこのゲームを開きます。": "Abre este juego en Chrome.",
  "右上の「⋮」メニューを開きます。": "Abre el menú ⋮ de arriba a la derecha.",
  "を選びます。表示が異なる場合は「インストールしてショートカットを作成」を選び、案内に沿って追加します。": ". Si el texto es distinto, elige instalar o crear un acceso directo y sigue las indicaciones.",
  "ChromeまたはEdgeでこのゲームを開きます。": "Abre este juego en Chrome o Edge.",
  "ブラウザーのメニューから、アプリのインストールやショートカットの作成を選びます。": "En el menú del navegador, elige instalar la aplicación o crear un acceso directo.",
  "画面の案内に沿って追加します。": "Sigue las indicaciones para terminar.",
  "ホーム画面から起動できています": "Ya has abierto el juego desde la pantalla de inicio",
  "追加の操作は必要ありません。そのまま遊べます。": "Todo listo. No hace falta hacer nada más.",
  "なにも持っていない。": "No llevas nada.",
  "かかった時間": "Tiempo",
  "音の大きさ": "Volumen",
  "視点の速さ": "Sensibilidad de la vista",
  "いま、すること": "Objetivo actual"
};
